from __future__ import annotations

import json
import pytest
from nexus.services.local_heal.p3_cloud_candidate_stub import (
    CloudCandidateStubResult,
    compute_cloud_candidate_stub,
    p3_cloud_stub_to_dict,
)


def _make_cloud_ready_diagnosis():
    return {
        "p3_diagnosis_cloud_ready": True,
        "p3_diagnosis_reason": "diagnosis_complete",
        "p3_diagnosis_compact_prompt_hash": "abc123",
        "p3_diagnosis_compact_prompt_token_estimate": 50,
    }


def _make_not_cloud_ready_diagnosis():
    return {
        "p3_diagnosis_cloud_ready": False,
        "p3_diagnosis_reason": "missing_anchor",
        "p3_diagnosis_compact_prompt_hash": "def456",
        "p3_diagnosis_compact_prompt_token_estimate": 30,
    }


# ============================================================
# P3-C-1: cloud_ready diagnosis creates cloud_call_planned=true
# ============================================================


def test_cloud_ready_creates_cloud_call_planned():
    stub = compute_cloud_candidate_stub(
        diagnosis_metadata=_make_cloud_ready_diagnosis(),
        cloud_provider="openai",
        cloud_model="gpt-4",
    )
    assert stub.cloud_call_planned is True
    assert stub.cloud_call_invoked is False
    assert stub.cloud_used is False
    assert stub.blocked_reason == ""


# ============================================================
# P3-C-2: cloud_call_invoked=false always
# ============================================================


def test_cloud_call_invoked_always_false():
    for ready in (True, False):
        diag = _make_cloud_ready_diagnosis() if ready else _make_not_cloud_ready_diagnosis()
        stub = compute_cloud_candidate_stub(diagnosis_metadata=diag)
        assert stub.cloud_call_invoked is False


# ============================================================
# P3-C-3: cloud_used=false always
# ============================================================


def test_cloud_used_always_false():
    for ready in (True, False):
        diag = _make_cloud_ready_diagnosis() if ready else _make_not_cloud_ready_diagnosis()
        stub = compute_cloud_candidate_stub(diagnosis_metadata=diag)
        assert stub.cloud_used is False


# ============================================================
# P3-C-4: no API key required
# ============================================================


def test_no_api_key_required():
    stub = compute_cloud_candidate_stub(diagnosis_metadata=_make_cloud_ready_diagnosis())
    assert stub.cloud_provider == "none"
    assert stub.cloud_model == "none"


# ============================================================
# P3-C-5: no candidate generated by default
# ============================================================


def test_no_candidate_generated_by_default():
    stub = compute_cloud_candidate_stub(diagnosis_metadata=_make_cloud_ready_diagnosis())
    assert stub.candidate_generated is False
    assert stub.candidate_source == "cloud_stub"


# ============================================================
# P3-C-6: non-cloud-ready diagnosis blocks with reason
# ============================================================


def test_non_cloud_ready_blocks_with_reason():
    stub = compute_cloud_candidate_stub(diagnosis_metadata=_make_not_cloud_ready_diagnosis())
    assert stub.cloud_call_planned is False
    assert "cloud_not_ready" in stub.blocked_reason
    assert "missing_anchor" in stub.blocked_reason


# ============================================================
# P3-C-7: candidate_source="cloud_stub"
# ============================================================


def test_candidate_source_cloud_stub():
    stub = compute_cloud_candidate_stub(diagnosis_metadata=_make_cloud_ready_diagnosis())
    assert stub.candidate_source == "cloud_stub"


# ============================================================
# P3-C-8: runtime_behavior_changed=false
# ============================================================


def test_runtime_behavior_changed_false():
    stub = compute_cloud_candidate_stub(diagnosis_metadata=_make_cloud_ready_diagnosis())
    assert stub.runtime_behavior_changed is False


# ============================================================
# P3-C-9: claim_eligible=false
# ============================================================


def test_claim_eligible_false():
    stub = compute_cloud_candidate_stub(diagnosis_metadata=_make_cloud_ready_diagnosis())
    assert stub.claim_eligible is False


# ============================================================
# P3-C-10: public_claim_allowed=false
# ============================================================


def test_public_claim_allowed_false():
    stub = compute_cloud_candidate_stub(diagnosis_metadata=_make_cloud_ready_diagnosis())
    assert stub.public_claim_allowed is False


# ============================================================
# P3-C-11: metadata JSON serializable
# ============================================================


def test_metadata_json_serializable():
    stub = compute_cloud_candidate_stub(diagnosis_metadata=_make_cloud_ready_diagnosis())
    meta = p3_cloud_stub_to_dict(stub)
    serialized = json.dumps(meta)
    assert isinstance(serialized, str)
    deserialized = json.loads(serialized)
    assert deserialized["p3_cloud_stub_call_planned"] is True


# ============================================================
# P3-C-12: Existing P3-B tests still pass
# ============================================================


def test_p3_b_still_works():
    from nexus.services.local_heal.p3_local_diagnosis import compute_p3_local_diagnosis
    diag = compute_p3_local_diagnosis(
        request_metadata={"task_id": "test"},
        anchor_metadata={"target_file": "foo.py"},
        hash_chain_metadata={"raw_output_hash": "h1", "normalized_patch_hash": "h2", "applied_patch_hash": "h3"},
    )
    assert diag.cloud_ready is True
