from __future__ import annotations

import ast
import hashlib
import json
from pathlib import Path
from typing import Iterable

from nexus.services.codeintel.models import CodeSkeletonLookupResult, CodeSkeletonSymbol


class PythonCodeSkeletonProvider:
    def __init__(self, root: str | Path, search_paths: Iterable[str | Path] = ()) -> None:
        self.root = Path(root).resolve()
        self.search_paths = tuple(Path(path) for path in search_paths)
        self._symbol_cache: dict[Path, list[CodeSkeletonSymbol]] = {}

    def lookup_implementation(self, symbol_name: str) -> CodeSkeletonLookupResult:
        target = symbol_name.strip()
        if not target:
            return CodeSkeletonLookupResult(symbol=symbol_name, found=False, reason="empty_symbol")
        matches = [
            symbol
            for path in self._python_files()
            for symbol in self._symbols_for_file(path)
            if symbol.symbol == target or symbol.symbol.endswith(f".{target}")
        ]
        if not matches:
            return CodeSkeletonLookupResult(symbol=target, found=False, reason="symbol_not_found")
        return CodeSkeletonLookupResult(symbol=target, found=True, matches=matches)

    def export_symbol_snapshot(self) -> dict[str, object]:
        symbols = [symbol.to_dict() for cached in self._symbol_cache.values() for symbol in cached]
        return {
            "schema": "nexus.code_skeleton_snapshot.v1",
            "root": str(self.root),
            "symbol_count": len(symbols),
            "snapshot_hash": _snapshot_hash(symbols),
            "symbols": symbols,
        }

    def load_symbol_snapshot(self, payload: dict[str, object]) -> None:
        if payload.get("schema") != "nexus.code_skeleton_snapshot.v1":
            raise ValueError("invalid_code_skeleton_snapshot_schema")
        raw_symbols = payload.get("symbols", [])
        if not isinstance(raw_symbols, list):
            raise ValueError("invalid_code_skeleton_snapshot_symbols")
        symbols = [_symbol_from_dict(item) for item in raw_symbols if isinstance(item, dict)]
        if _snapshot_hash([symbol.to_dict() for symbol in symbols]) != payload.get("snapshot_hash"):
            raise ValueError("code_skeleton_snapshot_hash_mismatch")
        self._symbol_cache = {}
        for symbol in symbols:
            path = self.root / symbol.file_path
            self._symbol_cache.setdefault(path, []).append(symbol)

    def _python_files(self) -> Iterable[Path]:
        roots = self.search_paths or (Path("."),)
        for root in roots:
            search_root = root if root.is_absolute() else self.root / root
            paths = [search_root] if search_root.is_file() else sorted(search_root.rglob("*.py"))
            for path in paths:
                if path.suffix != ".py":
                    continue
                if not path.exists() or _skip_path(path):
                    continue
                yield path

    def _symbols_for_file(self, path: Path) -> list[CodeSkeletonSymbol]:
        try:
            source = path.read_text(encoding="utf-8")
            tree = ast.parse(source)
        except SyntaxError:
            return [_with_ast_status(symbol, "LAST_KNOWN_GOOD") for symbol in self._symbol_cache.get(path, [])]
        except (OSError, UnicodeDecodeError):
            return []
        relative = path.relative_to(self.root)
        module = _module_name(relative)
        lines = source.splitlines()
        autogenerated = _is_autogenerated_python(path, source)
        symbols: list[CodeSkeletonSymbol] = []
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                symbols.append(_symbol(module, node, relative, lines, autogenerated=autogenerated))
            elif isinstance(node, ast.ClassDef):
                symbols.append(_symbol(module, node, relative, lines, autogenerated=autogenerated))
                for child in node.body:
                    if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        symbols.append(
                            _symbol(f"{module}.{node.name}", child, relative, lines, autogenerated=autogenerated)
                        )
        self._symbol_cache[path] = symbols
        return symbols


def lookup_implementation(
    root: str | Path,
    symbol_name: str,
    *,
    search_paths: Iterable[str | Path] = (),
) -> CodeSkeletonLookupResult:
    return PythonCodeSkeletonProvider(root, search_paths=search_paths).lookup_implementation(symbol_name)


def _symbol(
    prefix: str,
    node: ast.AST,
    relative: Path,
    lines: list[str],
    *,
    autogenerated: bool = False,
) -> CodeSkeletonSymbol:
    name = getattr(node, "name", "")
    kind = "class" if isinstance(node, ast.ClassDef) else "function"
    signature = _signature(node)
    return CodeSkeletonSymbol(
        symbol=f"{prefix}.{name}" if prefix else name,
        file_path=str(relative),
        start_line=int(getattr(node, "lineno", 0) or 0),
        end_line=int(getattr(node, "end_lineno", 0) or getattr(node, "lineno", 0) or 0),
        kind=kind,
        signature=signature,
        docstring_present=bool(ast.get_docstring(node)),
        rationale_context=() if autogenerated else _rationale_context(node, lines),
    )


def _signature(node: ast.AST) -> str:
    if isinstance(node, ast.ClassDef):
        bases = [ast.unparse(base) for base in node.bases]
        return f"class {node.name}({', '.join(bases)})" if bases else f"class {node.name}"
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
        return f"{prefix} {node.name}({_args(node.args)})"
    return ""


def _args(args: ast.arguments) -> str:
    rendered: list[str] = []
    rendered.extend(arg.arg for arg in args.posonlyargs)
    rendered.extend(arg.arg for arg in args.args)
    if args.vararg:
        rendered.append(f"*{args.vararg.arg}")
    rendered.extend(arg.arg for arg in args.kwonlyargs)
    if args.kwarg:
        rendered.append(f"**{args.kwarg.arg}")
    return ", ".join(rendered)


def _module_name(path: Path) -> str:
    parts = list(path.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts)


def _skip_path(path: Path) -> bool:
    return any(part in {".git", ".venv", "__pycache__", ".nexus-swarm-001"} for part in path.parts)


RATIONALE_PREFIXES = ("# NOTE:", "# HACK:", "# WHY:", "# IMPORTANT:", "# RATIONALE:")
AUTOGENERATED_MARKERS = (
    "auto-generated",
    "autogenerated",
    "generated by",
    "do not edit",
    "@generated",
)


def _rationale_context(node: ast.AST, lines: list[str]) -> tuple[str, ...]:
    rationale: list[str] = []
    docstring = ast.get_docstring(node)
    if docstring:
        rationale.append(docstring.strip())
    lineno = int(getattr(node, "lineno", 0) or 0)
    for line_number in range(max(1, lineno - 4), lineno):
        text = lines[line_number - 1].strip()
        if any(text.startswith(prefix) for prefix in RATIONALE_PREFIXES):
            rationale.append(text.lstrip("#").strip())
    return tuple(item for item in rationale if item)


def _is_autogenerated_python(path: Path, source: str) -> bool:
    lowered_path = "/".join(path.parts).lower()
    if "/migrations/" in lowered_path or lowered_path.endswith("_pb2.py") or lowered_path.endswith("_pb2_grpc.py"):
        return True
    head = "\n".join(source.splitlines()[:8]).lower()
    return any(marker in head for marker in AUTOGENERATED_MARKERS)


def _with_ast_status(symbol: CodeSkeletonSymbol, ast_status: str) -> CodeSkeletonSymbol:
    return CodeSkeletonSymbol(
        symbol=symbol.symbol,
        file_path=symbol.file_path,
        start_line=symbol.start_line,
        end_line=symbol.end_line,
        kind=symbol.kind,
        signature=symbol.signature,
        docstring_present=symbol.docstring_present,
        rationale_context=symbol.rationale_context,
        ast_status=ast_status,
    )


def _symbol_from_dict(payload: dict[str, object]) -> CodeSkeletonSymbol:
    return CodeSkeletonSymbol(
        symbol=str(payload.get("symbol") or ""),
        file_path=str(payload.get("file_path") or ""),
        start_line=int(payload.get("start_line") or 0),
        end_line=int(payload.get("end_line") or 0),
        kind=str(payload.get("kind") or ""),
        signature=str(payload.get("signature") or ""),
        docstring_present=bool(payload.get("docstring_present", False)),
        rationale_context=tuple(str(item) for item in payload.get("rationale_context", []) or []),
        ast_status=str(payload.get("ast_status") or "PARSED"),
    )


def _snapshot_hash(symbols: list[dict[str, object]]) -> str:
    payload = json.dumps(symbols, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()
