"""Phase 5 family canaries: MainchainEntry → CapabilityPlanner → UnifiedRuntime.

Each promotable capability gets family-specific positive + negative tasks.
Receipt is generated by the test (fails closed if missing) with honest
final_status derived from real pos/neg outcomes — not count-math theater.
"""

from __future__ import annotations

import json
import hashlib
import os
import shutil
import subprocess
import sys
import time
from collections import Counter
from functools import lru_cache
from pathlib import Path
from typing import Any, Mapping

import pytest

from nexus.services.capability_registry import (
    EXECUTION_CLASS_CONTROL_PLANE_REFERENCE,
    EXECUTION_CLASS_EXPERIMENTAL_NOT_PROMOTED,
    EXECUTION_CLASS_EXTERNAL_AUTH_REQUIRED,
    EXECUTION_CLASS_LEGACY_ALIAS,
    EXECUTION_CLASS_MISSING_ENGINE,
    LOCAL_STAGE_CAPABILITIES,
    PLANNER_EXECUTION_CONTRACTS,
    REAL_EXECUTION_CLASSES,
    _node_meta,
    list_planner_capability_names,
    project_local_execution_mode,
    project_online_execution_mode,
)
from nexus.evidence.receipt_base import audit_product_receipt_coverage
from nexus.services.mainchain_entry import run_mainchain
from nexus.services.mainchain_route_freeze import build_capability_catalog
from nexus.services.unified_runtime import (
    UnifiedRuntimeRequest,
    build_registered_online_invoker,
)

SCRATCH = Path(
    os.environ.get(
        "NEXUS_CLOSURE_SCRATCH",
        "/var/folders/ld/b61fwcys3x14s175ld5z1k9m0000gn/T/grok-goal-cc3bcf73f5ed/implementer",
    )
)
RECEIPT_PATH = SCRATCH / "nexus_all_capability_closure_receipt.json"
RECEIPT_TMP = Path("/tmp/nexus_all_capability_closure_receipt.json")

_SHALLOW_ACTIONS = frozenset(
    {
        "should_run",
        "health_check",
        "construct",
        "import_success",
        "probe",
        "fixture",
        "bind",
        "resolve",
        "resolve_service",
        "resolve_module",
        "resolve_providers",
        "cleanup",
    }
)


def _promotable_names() -> list[str]:
    out: list[str] = []
    for name in list_planner_capability_names():
        mat = _node_meta(name)["maturity"].lower()
        if mat in {"experimental", "deprecated", "legacy_alias", "unknown", "prototype"}:
            continue
        out.append(name)
    return out


def _family_positive_context(name: str) -> dict[str, Any]:
    """Family-specific positive context so real engines can succeed honestly."""
    import hashlib

    source_hash = hashlib.sha256(b"sealed-source-v1").hexdigest()
    verifier_artifact = "sha256:" + ("ab" * 32)
    base: dict[str, Any] = {
        "task_statement": f"family positive canary for {name}: scan impact risk codeintel",
        "task_type": "codeintel",
        "codeintel": {
            "scan_report_present": True,
            "impact_report_present": True,
            "risk_score": 3,
            "impacted_files_count": 1,
        },
        "semantic_status": "VERIFIED",
        "completion_status": "COMPLETE",
        "status": "VERIFIED",
        "verifier_status": "pass",
        "verifier_artifact": verifier_artifact,
        "source_hash": source_hash,
        "evidence_refs": [f"ev:pos:{name}"],
        "intent_pass": True,
        "risk_score": 1,
        "target_files": ["nexus/services/capability_registry.py"],
        "impact_map": {"nexus/services/capability_registry.py": []},
        "acceptance_criteria": ["tests_pass"],
        "deliverables": ["receipt"],
        "steps": ["inspect", "verify"],
        "handoff_readiness": 1.0,
        "escalate": True,
        "force_capability": name,
        "candidate_hash_matches_applied": True,
        "owner_approved": True,
        "candidate_target_file": "nexus/services/capability_registry.py",
        "capability_evidence_bundle": {
            "bundle_hash": "d" * 64,
            "source_hash": source_hash,
        },
        "online": {"invoked": True, "gate_passed": True},
        "verifier": {
            "task_id": f"pos-{name}",
            "invoked": True,
            "gate_passed": True,
            "verifier_status": "pass",
            "verifier_artifact": verifier_artifact,
            "source_hash": source_hash,
            "evidence_refs": [f"ev:pos:{name}"],
        },
    }
    return base


def _extract_cap_row(receipt: Mapping[str, Any], name: str) -> dict[str, Any]:
    rows = receipt.get("capabilities")
    if isinstance(rows, list):
        for item in rows:
            if isinstance(item, Mapping) and str(item.get("name") or "") == name:
                return dict(item)
    # alternate shapes
    caps = receipt.get("capability_results")
    if isinstance(caps, Mapping) and name in caps and isinstance(caps[name], Mapping):
        return dict(caps[name])
    return {}


def _consumer_proof(
    name: str,
    *,
    cap_row: Mapping[str, Any],
    receipt: Mapping[str, Any],
    consumer_effect: str,
) -> dict[str, Any]:
    """Observable consumer evidence keyed by consumer_effect."""
    evidence = list(cap_row.get("evidence_refs") or [])
    payload = cap_row.get("consumer_payload") if isinstance(cap_row.get("consumer_payload"), Mapping) else {}
    online = receipt.get("online") if isinstance(receipt.get("online"), Mapping) else {}
    ctx = receipt.get("context_trace") if isinstance(receipt.get("context_trace"), Mapping) else {}
    proof: dict[str, Any] = {
        "consumer_effect": consumer_effect,
        "evidence_refs_present": bool(evidence),
        "local_mode": project_local_execution_mode(name),
    }
    if consumer_effect == "PROMPT_EVIDENCE":
        proof["prompt_marker_or_payload"] = bool(payload) or bool(
            (ctx.get("online_received_context") or {})
        )
        proof["kind"] = "prompt_or_shared_evidence"
    elif consumer_effect == "EXECUTION_CONTROL":
        proof["control_receipt"] = bool(
            cap_row.get("invoked") is True
            and cap_row.get("gate_passed") is True
            and cap_row.get("outcome_contributed") is True
            and str(cap_row.get("semantic_status") or "")
            in {"SUCCEEDED", "VERIFIED"}
            and evidence
        )
        proof["kind"] = "execution_control_receipt"
    elif consumer_effect == "POSTFLIGHT_GATE":
        proof["gate_receipt"] = bool(
            cap_row.get("invoked") is True
            and cap_row.get("gate_passed") is True
            and str(cap_row.get("semantic_status") or "")
            in {"SUCCEEDED", "VERIFIED"}
            and evidence
        )
        proof["kind"] = "postflight_gate_receipt"
    elif consumer_effect == "EXTERNAL_SIDE_EFFECT":
        proof["side_effect_receipt"] = bool(
            str(cap_row.get("status") or "").startswith("BLOCK")
            or cap_row.get("skipped")
            or evidence
        )
        proof["kind"] = "side_effect_or_auth_block_receipt"
    else:
        proof["kind"] = "none"
        proof["control_plane_or_none"] = True
    proof["online_present"] = bool(online)
    return proof


def _local_live_proof_complete(
    *,
    name: str,
    auth_local: bool,
    invoked: bool,
    skipped: bool,
    gate: Any,
    local_stage: Mapping[str, Any],
    local_response: Mapping[str, Any],
    physical_callable: str,
) -> bool:
    """Fail closed on a complete Local model, isolation, hash, verifier receipt."""

    if name not in LOCAL_STAGE_CAPABILITIES or not auth_local:
        return False
    candidate = (
        local_response.get("candidate_summary")
        if isinstance(local_response.get("candidate_summary"), Mapping)
        else {}
    )
    verifier = (
        local_response.get("verifier_summary")
        if isinstance(local_response.get("verifier_summary"), Mapping)
        else {}
    )
    receipt_path = Path(str(local_response.get("receipt_path") or ""))
    try:
        receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
    except (OSError, ValueError, TypeError):
        receipt = {}
    return bool(
        invoked
        and not skipped
        and gate is True
        and str(local_stage.get("status") or "").upper()
        in {"SUCCEEDED", "SUCCESS", "VERIFIED", "COMPLETED", "OK", "INVOKED"}
        and not str(local_stage.get("reason") or "").strip()
        and local_response.get("provider") == "ollama"
        and str(local_response.get("physical_callable") or physical_callable)
        == "LocalModelExecutor.run"
        and local_response.get("local_model_invoked") is True
        and local_response.get("output_delivered") is True
        and not str(local_response.get("fallback_reason") or "").strip()
        and candidate.get("isolation_status") == "isolated"
        and candidate.get("selected_candidate_hash_matches_applied") is True
        and bool(candidate.get("selected_candidate_hash"))
        and candidate.get("selected_candidate_hash") == candidate.get("applied_patch_hash")
        and verifier.get("verifier_reached") is True
        and verifier.get("verifier_status") == "pass"
        and receipt.get("receipt_complete") is True
        and receipt.get("terminal_status") == "SUCCEEDED"
        and not str(receipt.get("fallback_reason") or "").strip()
    )


_REQUEST_EVIDENCE_KEYS = (
    "semantic_status",
    "completion_status",
    "status",
    "verifier_status",
    "verifier_artifact",
    "source_hash",
    "evidence_refs",
    "intent_pass",
    "risk_score",
    "target_files",
    "impact_map",
    "acceptance_criteria",
    "deliverables",
    "steps",
    "handoff_readiness",
    "candidate_hash_matches_applied",
    "owner_approved",
    "candidate_target_file",
    "force_capability",
    "escalate",
)


@lru_cache(maxsize=None)
def _run_family_canary(
    name: str,
    *,
    positive: bool,
    task_id_override: str = "",
) -> dict[str, Any]:
    """Single MainchainEntry canary — gate/status only from receipt capability row."""
    contract = PLANNER_EXECUTION_CONTRACTS[name]
    family_ctx = _family_positive_context(name) if positive else {}
    if positive and not family_ctx.get("source_hash"):
        family_ctx["source_hash"] = hashlib.sha256(b"sealed-canary-source-v1").hexdigest()
    task_id = str(task_id_override or f"{'pos' if positive else 'neg'}-{name}")
    canary_root = Path("/tmp/nexus_family_canary") / task_id
    canary_root.mkdir(parents=True, exist_ok=True)
    canary_target = canary_root / "target.py"
    canary_target.write_text(
        (
            "def family_canary_target():\n    return 'broken'\n"
            if positive and name in LOCAL_STAGE_CAPABILITIES
            else "def family_canary_target():\n    return 'verified'\n"
        ),
        encoding="utf-8",
    )
    if positive and name in {"semantic_searcher", "lancedb"}:
        from nexus.services.memory_repository import MemoryRepository

        memory_root = canary_root / ".nexus" / "knowledge" / "lancedb"
        memory_repository = MemoryRepository(memory_root)
        # A prior interrupted canary can leave an empty ``policy.lance``
        # directory that LanceDB lists but cannot open.  Repair only this
        # generated /tmp canary artifact, then recreate the bounded fixture
        # input; never touch a user workspace database.
        try:
            memory_repository.search_fts(
                "policy", "capability closure", limit=1, fallback_columns=["condition"]
            )
        except Exception:
            stale_table = memory_root / "policy.lance"
            if stale_table.exists():
                shutil.rmtree(stale_table)
            memory_repository = MemoryRepository(memory_root)
        memory_repository.ensure_table(
            "policy",
            initial_data=[
                {
                    "rule_id": f"family-policy-{name}",
                    "condition": "capability closure",
                    "action": f"physical evidence for {name}",
                    "confidence": 0.9,
                }
            ],
            fts_column="action",
        )
    trigger_policy = str(contract.get("trigger_policy") or "")
    postflight = name in {"artifact_gate", "claim_gate", "delivery_gate"}
    acceptance_family = name in {"acceptance_check", "bdd_acceptance_skill"}
    default_when_selected = trigger_policy in {
        "default_when_selected",
        "stage_owned_local",
        "stage_owned_context",
    } and not postflight and not acceptance_family
    if positive:
        statement = (
            f"Capability family canary for {name}.\n"
            f"Expected capability receipts: {name}"
        )
    elif default_when_selected:
        statement = "Negative family canary with no optional capability signal."
    else:
        statement = (
            "Negative capability family canary with missing evidence.\n"
            f"Expected capability receipts: {name}"
        )
    if positive and name in LOCAL_STAGE_CAPABILITIES:
        statement = (
            "Repair target.py so family_canary_target returns exactly 'verified'.\n"
            f"Expected capability receipts: {name}"
        )
    # Positive escalate: route flags; negative: no escalate flags.
    # When external live is authorized, allow Online so postflight can consume real online output.
    auth_ext_route = os.environ.get("NEXUS_EXTERNAL_RUNTIME_AUTHORIZED", "").strip() == "1"
    # Production Online provider: default agy; operator may set NEXUS_ONLINE_PROVIDER=grok
    # when agy is quota-blocked (user-authorized substitute, not Gemini/API-key).
    online_provider = (
        os.environ.get("NEXUS_ONLINE_PROVIDER")
        or os.environ.get("NEXUS_CLOUD_PROVIDER")
        or "agy"
    ).strip().lower() or "agy"
    if online_provider not in {"agy", "grok", "codex", "gemini", "openai"}:
        online_provider = "agy"
    route: dict[str, Any] = {
        "recommended_flow": "direct",
        "provider": online_provider,
        # auto/require are the only authorizing task policies; "allow" is not a policy token
        "online_policy": ("auto" if (positive and auth_ext_route) else "deny"),
        "mainchain_entry": True,
        "workspace_root": str(canary_root),
    }
    if positive:
        route["escalate"] = True
        route["escalate_triggered"] = True

    # The negative arm must not invoke the Local stage.  Keeping it enabled here
    # makes an authorized Ollama run execute both positive and negative arms,
    # turning a valid live proof into a false negative (negative_not_skip_or_fail).
    local_enabled = positive and name in LOCAL_STAGE_CAPABILITIES
    local_action = "verified-subtask" if name in LOCAL_STAGE_CAPABILITIES else "candidate"
    from nexus.services.local_assist_service import LocalAssistRequest

    req = UnifiedRuntimeRequest(
        task_id=task_id,
        workspace_revision="rev-family-canary",
        task_statement=str(statement),
        task_type=str(family_ctx.get("task_type") or "codeintel"),
        route=route,
        online_enabled=True,
        # Local stage only when exercising local_model_executor ownership.
        local_enabled=local_enabled,
        local_request=LocalAssistRequest.from_dict({
            "schema": "nexus.local_assist.request.v1",
            "task_id": task_id,
            "parent_task_id": task_id,
            "workspace_root": str(canary_root),
            "workspace_revision": "rev-family-canary",
            "task_statement": statement,
            "action": local_action,
            "allowed_files": ["target.py"],
            "target_file": "target.py",
            "target_symbol": "family_canary_target",
            "evidence_refs": [f"family-canary:{name}"],
            "verifier_command": [
                sys.executable,
                "-c",
                (
                    "ns={}; exec(open('target.py', encoding='utf-8').read(), ns); "
                    "assert ns['family_canary_target']() == 'verified'"
                ),
            ]
            if local_action == "verified-subtask"
            else [],
            "requested_role": "candidate",
            "mutation_policy": "isolated_only",
            "planner_snapshot": {
                "route_truth_source": "CapabilityPlanner",
                "selected_capabilities": [name] if positive else [],
                "execution_topology": "single_local_model",
                "protocol_mode": "code_patch",
                "model_call_allowed": True,
                "executor_provider": "ollama",
                "executor_model": "qwen2.5-coder:7b-instruct",
            },
        })
        if local_enabled
        else None,
        online_prompt="family canary",
        codeintel=(
            {
                **dict(family_ctx.get("codeintel") or {}),
                "workspace_root": str(canary_root),
                "target_file": "target.py",
                "target_symbol": "family_canary_target",
                "verify_commands": [
                    f"{sys.executable} -m py_compile target.py"
                ],
                "verify_timeout_sec": 15,
                "search_query": f"physical evidence for {name}",
                "search_table": "policy",
                "search_limit": 3,
                "jit_all_tools": ["read_file", "run_test", "write_file"],
                "jit_token_usage": 120,
                "mempalace_tenant_id": "family-canary",
                "mempalace_artifact_type": "capability_evidence",
                "mempalace_artifact": {
                    "artifact_id": f"closure-evidence-{name}",
                    "content": f"capability closure verified for {name}",
                    "source_hash": hashlib.sha256(
                        canary_target.read_bytes()
                    ).hexdigest(),
                },
                "mempalace_query": f"closure-evidence-{name}",
                "sandbox_command": [
                    sys.executable,
                    "-c",
                    "from pathlib import Path; assert Path('target.py').exists()",
                ],
                "sandbox_timeout_sec": 15,
                "metabolism_token_usage": 110000,
                "metabolism_token_limit": 128000,
                "intent_pass": True,
                "risk_score": 1,
                "target_files": ["target.py"],
                "impact_map": {"target.py": []},
                "acceptance_criteria": ["isolated verifier passes"],
                "deliverables": ["family canary receipt"],
                "steps": ["inspect", "verify"],
                "handoff_readiness": 1.0,
                "asi_failure_records": [
                    {
                        "status": "discard",
                        "family": "family_canary_repeated_failure",
                        "rollback_reason": "same verifier mismatch",
                        "evidence": f"asi:{name}:failure:1",
                        "run_id": f"{task_id}:1",
                    },
                    {
                        "status": "discard",
                        "family": "family_canary_repeated_failure",
                        "rollback_reason": "same verifier mismatch",
                        "evidence": f"asi:{name}:failure:2",
                        "run_id": f"{task_id}:2",
                    },
                ],
                "forecast_roi_score": 0.9,
                "forecast_tokens": 1000,
                "forecast_reject_prob": 0.05,
                "formal_judge_votes": [
                    {"judge": "deterministic_hard", "verdict": "PASS"}
                ],
                "formal_verification": [
                    {"status": "PASS", "evidence": f"isolated-verifier:{task_id}"}
                ],
                "formal_route_receipts": [
                    {
                        "route": "mainchain",
                        "evidence_present": True,
                        "gate_passed": True,
                    }
                ],
                "meta_opt_episode": {
                    "task_id": task_id,
                    "task_type": "codeintel",
                    "task_desc": statement,
                    "solved": True,
                    "wall_duration_sec": 0.1,
                    "total_tokens_used": 0,
                    "trust_mismatch": False,
                    "receipts": [
                        {
                            "name": "codeintel",
                            "invoked": True,
                            "gate_passed": True,
                            "outcome_contributed": True,
                        }
                    ],
                },
            }
            if positive
            else {"scan_report_present": False}
        ),
        pillars={
            # Family evidence may also ride pillars for preflight allowlists.
            **(
                {
                    k: family_ctx[k]
                    for k in _REQUEST_EVIDENCE_KEYS
                    if k in family_ctx
                }
                if positive
                else {}
            )
        },
    )
    # Negative selection strategy (honest, no dual probe):
    # - escalate/triggered policies: select but untriggered → SKIP
    # - postflight/acceptance: select with missing evidence → FAIL
    # - default_when_selected: do NOT select (untriggered at planner) → not executed
    from nexus.services.capability_registry import build_default_mainchain_invokers
    from nexus.services.local_assist_service import LocalAssistService

    invoker_map = build_default_mainchain_invokers(
        codeintel=dict(req.codeintel) if isinstance(req.codeintel, Mapping) else {}
    )

    def _verifier(c: Mapping[str, Any]) -> dict[str, Any]:
        from nexus.services.local_heal.isolated_verifier import (
            IsolatedVerifierRequest,
            run_isolated_verifier,
        )

        bundle = c.get("capability_evidence_bundle") if isinstance(c.get("capability_evidence_bundle"), Mapping) else {}
        src = str(bundle.get("source_hash") or "")
        command = (
            sys.executable,
            "-c",
            (
                (
                    "ns={}; exec(open('target.py', encoding='utf-8').read(), ns); "
                    "assert ns['family_canary_target']() == 'broken'"
                    if name in LOCAL_STAGE_CAPABILITIES
                    else "from pathlib import Path; "
                    "source=Path('target.py').read_text(encoding='utf-8'); "
                    "compile(source, 'target.py', 'exec'); "
                    "assert 'family_canary_target' in source"
                )
                if positive
                else "raise SystemExit(1)"
            ),
        )
        isolated = run_isolated_verifier(
            IsolatedVerifierRequest(
                task_id=str(c.get("task_id") or task_id),
                workspace_path=str(canary_root),
                verifier_command=command,
                timeout_sec=15.0,
                verifier_allowed=True,
            )
        )
        passed = isolated.verifier_status == "pass" and isolated.exit_code == 0
        artifact_payload = json.dumps(
            {
                "task_id": isolated.task_id,
                "exit_code": isolated.exit_code,
                "stdout_tail": isolated.stdout_tail,
                "stderr_tail": isolated.stderr_tail,
                "source_hash": src,
                "command": list(command),
            },
            sort_keys=True,
        ).encode("utf-8")
        return {
            "task_id": str(c.get("task_id") or task_id),
            "invoked": True,
            "gate_passed": passed,
            "semantic_status": "VERIFIED" if passed else "UNVERIFIED",
            "verifier_status": isolated.verifier_status,
            "verifier_artifact": (
                "sha256:" + hashlib.sha256(artifact_payload).hexdigest()
                if passed
                else ""
            ),
            "source_hash": src if passed else "",
            "evidence_refs": [f"isolated-verifier:{isolated.task_id}"],
            "exit_code": isolated.exit_code,
            "verifier_error": isolated.verifier_error,
            "physical_callable": (
                "nexus.services.local_heal.isolated_verifier."
                "run_isolated_verifier"
            ),
        }

    receipt = run_mainchain(
        req,
        online_invoker=build_registered_online_invoker(online_provider),
        local_service=LocalAssistService() if local_enabled else None,
        capability_invokers=invoker_map,
        verifier=_verifier,
        learning=None,
    )

    # ── Truth only from MainchainEntry receipt (no second invoker probe) ──
    ctx_trace = receipt.get("context_trace") if isinstance(receipt.get("context_trace"), Mapping) else {}
    online_stage = receipt.get("online") if isinstance(receipt.get("online"), Mapping) else {}
    online_response = (
        online_stage.get("response")
        if isinstance(online_stage.get("response"), Mapping)
        else {}
    )
    verifier_stage = receipt.get("verifier") if isinstance(receipt.get("verifier"), Mapping) else {}
    verifier_response = (
        verifier_stage.get("response")
        if isinstance(verifier_stage.get("response"), Mapping)
        else {}
    )
    local_stage = receipt.get("local") if isinstance(receipt.get("local"), Mapping) else {}
    local_response = (
        local_stage.get("response")
        if isinstance(local_stage.get("response"), Mapping)
        else {}
    )
    local_stage_status = str(local_stage.get("status") or "")
    selected = [str(x) for x in (ctx_trace.get("selected_capabilities") or receipt.get("selected_capabilities") or [])]
    cap_row = _extract_cap_row(receipt, name)
    # Prefer capability_results stage status when list row is thin
    cap_results = receipt.get("capability_results") if isinstance(receipt.get("capability_results"), Mapping) else {}
    stage = cap_results.get(name) if isinstance(cap_results.get(name), Mapping) else {}

    invoked = bool(cap_row.get("invoked") if "invoked" in cap_row else stage.get("invoked"))
    skipped = bool(cap_row.get("skipped") if "skipped" in cap_row else stage.get("skipped"))
    gate = cap_row.get("gate_passed")
    if gate is None:
        gate = stage.get("gate_passed")
    status = str(
        cap_row.get("status")
        or stage.get("status")
        or ""
    )
    physical = str(
        cap_row.get("physical_callable")
        or stage.get("physical_callable")
        or ""
    )
    # Nested response/outcome from stage if present
    response = stage.get("response") if isinstance(stage.get("response"), Mapping) else {}
    inner_response: Mapping[str, Any] = response
    for _ in range(3):
        if isinstance(inner_response.get("outcome"), Mapping):
            break
        next_response = inner_response.get("response")
        if not isinstance(next_response, Mapping):
            break
        inner_response = next_response
    nested = (
        inner_response.get("outcome")
        if isinstance(inner_response.get("outcome"), Mapping)
        else inner_response
    )
    if not nested and isinstance(cap_row.get("response"), Mapping):
        nested = dict(cap_row["response"])
    action = str((nested or {}).get("action") or "")
    semantic_status = str((nested or {}).get("semantic_status") or "")
    outcome_error = str((nested or {}).get("error") or "")
    outcome_auth_required = bool(
        (nested or {}).get("authorization_required")
        or (nested or {}).get("auth_required")
    )
    outcome_contributed = bool(
        cap_row.get("outcome_contributed")
        or stage.get("outcome_contributed")
        or (nested or {}).get("outcome_contributed")
    )
    contract_violations = list(
        inner_response.get("contract_violations") or []
        if isinstance(inner_response, Mapping)
        else []
    )
    evidence = list(
        dict.fromkeys(
            [
                str(ref)
                for ref in (
                    list(cap_row.get("evidence_refs") or [])
                    + list(stage.get("evidence_refs") or [])
                    + list((nested or {}).get("evidence_refs") or [])
                )
                if str(ref)
            ]
        )
    )

    # mainchain_entry proven from receipt (not hardcoded): route stamp and/or planner stage.
    planner_stage = receipt.get("planner") if isinstance(receipt.get("planner"), Mapping) else {}
    selection_authority = str(receipt.get("selection_authority") or "")
    planner_decision_id = str(
        receipt.get("planner_decision_id")
        or planner_stage.get("planner_decision_id")
        or ""
    )
    online_ctx = (
        ctx_trace.get("online_received_context")
        if isinstance(ctx_trace.get("online_received_context"), Mapping)
        else {}
    )
    route_stamp = {}
    if isinstance(receipt.get("context_trace"), Mapping) and isinstance(
        receipt["context_trace"].get("route"), Mapping
    ):
        route_stamp = dict(receipt["context_trace"]["route"])
    shared_stage: Mapping[str, Any] = {}
    for receipt_stage in receipt.get("stages") or []:
        if (
            isinstance(receipt_stage, Mapping)
            and receipt_stage.get("name") == "shared_capability_evidence"
        ):
            shared_stage = receipt_stage
            break
    mainchain_entry_real = bool(
        route_stamp.get("mainchain_entry") is True
        and planner_stage.get("invoked") is True
        and selection_authority == "CapabilityPlanner"
        and planner_decision_id
        and shared_stage.get("invoked") is True
        and shared_stage.get("gate_passed") is True
        and shared_stage.get("bundle_hash")
    )
    # When the capability was selected, require a mainchain capability row.
    if name in selected and not cap_row and not stage:
        mainchain_entry_real = False
    ec = str(contract["execution_class"])
    consumer_effect = str(contract["consumer_effect"])
    consumer_source = {
        **dict(stage),
        **dict(cap_row),
        "invoked": invoked,
        "skipped": skipped,
        "gate_passed": gate,
        "semantic_status": semantic_status,
        "outcome_contributed": outcome_contributed,
        "evidence_refs": evidence,
    }
    consumer = _consumer_proof(
        name,
        cap_row=consumer_source,
        receipt=receipt,
        consumer_effect=consumer_effect,
    )

    first_broken: str | None = None
    final_status = "OK"

    if not mainchain_entry_real:
        first_broken = "mainchain_entry_not_proven"
        final_status = "FAIL"
    if name not in selected and positive:
        alias_target = ""
        if ec == EXECUTION_CLASS_LEGACY_ALIAS:
            policy = str(contract.get("trigger_policy") or "")
            if policy.startswith("legacy_alias_of:"):
                alias_target = policy.split(":", 1)[1]
        if alias_target and alias_target in selected:
            first_broken = None
            final_status = "ALIAS_NORMALIZED"
        else:
            first_broken = first_broken or "not_selected_by_planner"
            final_status = "FAIL"
    if "fixture" in physical.lower() or physical.startswith("test:"):
        first_broken = first_broken or "fixture_callable"
        final_status = "FAIL"
    if action in _SHALLOW_ACTIONS and positive and bool(gate):
        first_broken = first_broken or f"probe_only_success:{action}"
        final_status = "PROBE"

    if positive:
        if (
            bool(contract.get("provider_authorization_required"))
            and ec != EXECUTION_CLASS_LEGACY_ALIAS
        ):
            observed_auth_block = bool(
                invoked
                and not skipped
                and gate is False
                and action == "auth_gate"
                and semantic_status == "BLOCKED"
                and outcome_auth_required
                and outcome_error.startswith("BLOCKED_EXTERNAL_AUTH")
                and evidence
                and not outcome_contributed
            )
            observed_local_auth_block = bool(
                name in LOCAL_STAGE_CAPABILITIES
                and local_response
                and local_response.get("provider") == "ollama"
                and local_response.get("physical_callable") == "LocalModelExecutor.run"
                and local_response.get("fallback_reason") == "provider_not_configured"
                and local_response.get("local_model_invoked") is False
                and local_response.get("output_delivered") is False
            )
            auth_local = os.environ.get("NEXUS_LOCAL_MODEL_CALL_ALLOWED", "").strip() == "1"
            auth_ext = os.environ.get("NEXUS_EXTERNAL_RUNTIME_AUTHORIZED", "").strip() == "1"
            observed_local_live_ok = _local_live_proof_complete(
                name=name,
                auth_local=auth_local,
                invoked=invoked,
                skipped=skipped,
                gate=gate,
                local_stage=local_stage,
                local_response=local_response,
                physical_callable=physical,
            )
            observed_external_live_ok = bool(
                auth_ext
                and name not in LOCAL_STAGE_CAPABILITIES
                and invoked
                and not skipped
                and gate is True
                and action != "auth_gate"
                and semantic_status in {"SUCCEEDED", "VERIFIED", ""}
                and evidence
                and action not in _SHALLOW_ACTIONS
            )
            if final_status != "OK":
                pass
            elif observed_auth_block:
                first_broken = None
                final_status = "AUTH_BLOCKED"
            elif observed_local_auth_block:
                first_broken = None
                final_status = "AUTH_BLOCKED"
            elif observed_local_live_ok:
                # Authorized live Local success (Ollama physical path proven)
                first_broken = None
                final_status = "OK"
            elif observed_external_live_ok:
                # Authorized live Online/external success (non-auth_gate action)
                first_broken = None
                final_status = "OK"
            elif name in {"claim_gate", "delivery_gate"} and (
                gate is False and "blocker:online_not_invoked" in evidence
            ):
                if auth_ext:
                    first_broken = "online_authorized_but_not_invoked"
                    final_status = "FAIL"
                else:
                    first_broken = "online_not_exercised_offline"
                    final_status = "NOT_EXERCISED_OFFLINE"
            elif name in LOCAL_STAGE_CAPABILITIES and not invoked:
                local_stage = receipt.get("local") if isinstance(receipt.get("local"), Mapping) else {}
                first_broken = str(local_stage.get("reason") or "local_stage_not_executed")
                final_status = "IMPLEMENTATION_FAILURE"
            elif gate is True and invoked and not skipped:
                # Offline canaries must not silently accept provider success without auth flags
                if not auth_local and not auth_ext:
                    first_broken = first_broken or "offline_canary_unexpected_provider_success"
                    final_status = "FAIL"
                elif name in LOCAL_STAGE_CAPABILITIES and auth_local:
                    first_broken = first_broken or "local_authorized_incomplete_live_proof"
                    final_status = "FAIL"
                elif auth_ext:
                    first_broken = first_broken or "external_authorized_incomplete_live_proof"
                    final_status = "FAIL"
                else:
                    first_broken = first_broken or "offline_canary_unexpected_provider_success"
                    final_status = "FAIL"
            else:
                # Authorized but still blocked by policy/SLO/env (not pure missing auth flag)
                if auth_ext or auth_local:
                    # Honest operational residual when executor ran but gate failed
                    if invoked and gate is False and action != "auth_gate":
                        first_broken = first_broken or (
                            outcome_error
                            or semantic_status
                            or "authorized_executor_blocked"
                        )
                        final_status = "OPERATIONAL_BLOCKED"
                    elif invoked and gate is False and action == "auth_gate":
                        # Still auth-blocked despite flags (sub-capability gate)
                        first_broken = None
                        final_status = "AUTH_BLOCKED"
                    elif invoked and action in {"cleanup", "no_op", "skip"}:
                        first_broken = first_broken or f"authorized_no_op:{action}"
                        final_status = "OPERATIONAL_BLOCKED"
                    else:
                        first_broken = first_broken or "authorization_block_not_observed"
                        final_status = "IMPLEMENTATION_FAILURE"
                else:
                    first_broken = first_broken or "authorization_block_not_observed"
                    final_status = "IMPLEMENTATION_FAILURE"
        elif ec in REAL_EXECUTION_CLASSES:
            if not invoked and not skipped:
                first_broken = first_broken or "real_not_invoked"
                final_status = "FAIL"
            # Gate/status must come from MainchainEntry row — fail if gate false.
            if gate is False or status in {"FAILED", "BLOCKED", "BLOCKED_EXECUTOR_UNAVAILABLE"}:
                first_broken = first_broken or f"real_positive_mainchain_failed:{status or gate}"
                final_status = "FAIL"
            if not evidence and not skipped:
                first_broken = first_broken or "missing_evidence_refs"
                final_status = "FAIL"
            if not physical:
                # Local-stage-owned may only appear on local stage; allow delegated skip
                # only when not local_model_executor success path.
                if name == "local_model_executor":
                    # Must actually invoke Local stage physical path when positive.
                    local_stage = receipt.get("local") if isinstance(receipt.get("local"), Mapping) else {}
                    local_phys = ""
                    if isinstance(local_stage.get("response"), Mapping):
                        local_phys = str(local_stage["response"].get("physical_callable") or "")
                    if local_phys or (invoked and gate is True):
                        physical = local_phys or "local_stage:LocalModelExecutor"
                    else:
                        first_broken = first_broken or "local_model_executor_not_physically_invoked"
                        final_status = "FAIL"
                else:
                    first_broken = first_broken or "missing_physical_callable"
                    final_status = "FAIL"
        elif ec == EXECUTION_CLASS_EXTERNAL_AUTH_REQUIRED:
            semantic_ok = semantic_status in {"SUCCEEDED", "VERIFIED"}
            operational_block = bool(
                name == "learn_scheduler"
                and invoked
                and not skipped
                and gate is False
                and action == "run_scheduler"
                and semantic_status == "BLOCKED"
                and outcome_error in {"scheduler_exit_2", "scheduler_exit_3"}
                and any(ref.startswith("file:") for ref in evidence)
                and physical
            )
            if operational_block:
                first_broken = "scheduler_policy_not_ready"
                final_status = "OPERATIONAL_BLOCKED"
            elif contract_violations:
                first_broken = first_broken or "execution_contract_violation"
                final_status = "IMPLEMENTATION_FAILURE"
            elif not invoked or skipped or gate is not True:
                first_broken = first_broken or "external_capability_not_successful"
                final_status = "IMPLEMENTATION_FAILURE"
            elif not semantic_ok or not evidence or not physical:
                first_broken = first_broken or "external_capability_missing_semantic_evidence"
                final_status = "IMPLEMENTATION_FAILURE"
            elif action in _SHALLOW_ACTIONS:
                first_broken = first_broken or "external_auth_probe_success"
                final_status = "IMPLEMENTATION_FAILURE"
        elif ec == EXECUTION_CLASS_CONTROL_PLANE_REFERENCE:
            pass  # suggestion / skip is acceptable
        elif ec == EXECUTION_CLASS_LEGACY_ALIAS:
            pass
        elif ec == EXECUTION_CLASS_EXPERIMENTAL_NOT_PROMOTED:
            pass
    else:
        # Negative: untriggered skip OR missing-evidence FAIL OR unselected (default).
        if ec in REAL_EXECUTION_CLASSES:
            unselected = name not in selected
            neg_ok = bool(
                unselected
                or skipped
                or gate is False
                or status in {"FAILED", "BLOCKED", "SKIPPED", "SELECTED_NOT_EXECUTED"}
                or (not invoked and not gate)
            )
            if not neg_ok:
                first_broken = first_broken or (
                    f"negative_not_skip_or_fail:status={status}:gate={gate}:invoked={invoked}"
                )
                final_status = "FAIL"
            # Explicit false-green: selected + success on negative is never OK.
            if (
                name in selected
                and gate is True
                and invoked
                and status in {"SUCCEEDED", "INVOKED"}
                and not skipped
            ):
                first_broken = first_broken or "negative_false_green_success"
                final_status = "FAIL"
        elif ec == EXECUTION_CLASS_EXTERNAL_AUTH_REQUIRED:
            pass

    if contract.get("public_claim_allowed") is not False:
        first_broken = first_broken or "public_claim_allowed_not_false"
        final_status = "FAIL"
    public_claim = receipt.get("claim_boundary") if isinstance(receipt.get("claim_boundary"), Mapping) else {}
    if public_claim.get("public_claim_allowed") is True or receipt.get("public_claim_allowed") is True:
        first_broken = first_broken or "receipt_public_claim_true"
        final_status = "FAIL"

    return {
        "capability": name,
        "positive": positive,
        "execution_class": ec,
        "consumer_effect": consumer_effect,
        "selected": selected,
        "planner_selected": name in selected,
        "invoked": invoked,
        "skipped": skipped,
        "gate_passed": gate,
        "status": status,
        "physical_callable": physical,
        "action": action,
        "semantic_status": semantic_status,
        "outcome_error": outcome_error,
        "outcome_auth_required": outcome_auth_required,
        "outcome_contributed": outcome_contributed,
        "local_stage_status": str(local_stage.get("status") or ""),
        "local_stage_reason": str(local_stage.get("reason") or ""),
        "local_provider": str(local_response.get("provider") or ""),
        "local_fallback_reason": str(local_response.get("fallback_reason") or ""),
        "contract_violations": contract_violations,
        "evidence_refs": evidence[:8],
        "consumer_proof": consumer,
        "mainchain_entry": bool(mainchain_entry_real),
        "selection_authority": selection_authority,
        "planner_decision_id": planner_decision_id,
        "online_provider": str(online_response.get("provider") or ""),
        "online_provider_call_count": int(
            online_response.get("provider_call_count") or 0
        ),
        "online_gate_passed": bool(online_stage.get("gate_passed")),
        "verifier_physical_callable": str(
            verifier_response.get("physical_callable") or ""
        ),
        "verifier_exit_code": verifier_response.get("exit_code"),
        "verifier_status": str(verifier_response.get("verifier_status") or ""),
        "verifier_artifact": str(
            verifier_response.get("verifier_artifact") or ""
        ),
        "public_claim_allowed": False,
        "first_broken_edge": first_broken,
        "final_status": final_status,
        "mainchain_cap_row": {
            "invoked": invoked,
            "skipped": skipped,
            "gate_passed": gate,
            "status": status,
            "physical_callable": physical,
            "selection_source": cap_row.get("selection_source"),
        },
        # Test-only raw receipt handoff for stricter downstream closure
        # adapters.  The production receipt remains the sole truth source.
        "_raw_receipt": receipt,
    }


def build_and_write_closure_receipt() -> dict[str, Any]:
    """Generate honest closure receipt (SCRATCH + /tmp mirror)."""
    SCRATCH.mkdir(parents=True, exist_ok=True)
    root = Path(__file__).resolve().parents[2]
    catalog = build_capability_catalog(repo_root=root)
    promotable = _promotable_names()
    per_cap: list[dict[str, Any]] = []
    probe_only = 0
    fixture_count = 0
    real_positive_fails = 0

    for name in list_planner_capability_names():
        contract = PLANNER_EXECUTION_CONTRACTS[name]
        pos = _run_family_canary(name, positive=True)
        neg = _run_family_canary(name, positive=False)
        # Merge: fail if either broken for promotable REAL
        first_broken = pos.get("first_broken_edge") or neg.get("first_broken_edge")
        final_status = str(pos["final_status"])
        if neg["final_status"] != "OK":
            final_status = neg["final_status"]
        if pos.get("action") in _SHALLOW_ACTIONS and pos.get("gate_passed"):
            probe_only += 1
        phys = str(pos.get("physical_callable") or "")
        if "fixture" in phys.lower() or phys.startswith("test:"):
            fixture_count += 1
        if (
            name in promotable
            and contract["execution_class"] in REAL_EXECUTION_CLASSES
            and pos["final_status"]
            in {"FAIL", "PROBE", "IMPLEMENTATION_FAILURE"}
        ):
            real_positive_fails += 1
        per_cap.append(
            {
                "capability": name,
                "execution_class": contract["execution_class"],
                "maturity": _node_meta(name)["maturity"],
                "promotable": name in promotable,
                "gap_proxy": contract["execution_class"],
                "local_mode": project_local_execution_mode(name),
                "online_mode": project_online_execution_mode(name),
                "provider_authorization_required": bool(
                    contract.get("provider_authorization_required")
                ),
                "consumer_effect": contract["consumer_effect"],
                "public_claim_allowed": False,
                "positive": {
                    k: pos[k]
                    for k in (
                        "invoked",
                        "skipped",
                        "gate_passed",
                        "status",
                        "physical_callable",
                        "action",
                        "evidence_refs",
                        "consumer_proof",
                        "planner_selected",
                        "mainchain_entry",
                        "local_stage_status",
                        "local_stage_reason",
                        "local_provider",
                        "local_fallback_reason",
                    )
                },
                "negative": {
                    k: neg[k]
                    for k in (
                        "invoked",
                        "skipped",
                        "gate_passed",
                        "status",
                        "action",
                        "evidence_refs",
                        "consumer_proof",
                    )
                },
                "first_broken_edge": first_broken,
                "final_status": final_status,
            }
        )

    ec_counts = Counter(c["execution_class"] for c in PLANNER_EXECUTION_CONTRACTS.values())
    prom_missing = [
        n
        for n in promotable
        if PLANNER_EXECUTION_CONTRACTS[n]["execution_class"] == EXECUTION_CLASS_MISSING_ENGINE
    ]
    blockers = [
        r for r in per_cap if r["final_status"] not in {"OK", "ALIAS_NORMALIZED"}
    ]
    structural_blockers = [
        r
        for r in per_cap
        if r["final_status"] in {"FAIL", "PROBE", "IMPLEMENTATION_FAILURE"}
    ]
    semantic_blockers = [
        r
        for r in per_cap
        if r["promotable"]
        and r["execution_class"]
        in {*REAL_EXECUTION_CLASSES, EXECUTION_CLASS_EXTERNAL_AUTH_REQUIRED}
        and r["final_status"] != "OK"
    ]
    structural = (
        len(list_planner_capability_names()) == 57
        and len(prom_missing) == 0
        and probe_only == 0
        and fixture_count == 0
        and real_positive_fails == 0
        and not structural_blockers
    )
    semantic = not semantic_blockers
    auth_ext = os.environ.get("NEXUS_EXTERNAL_RUNTIME_AUTHORIZED", "").strip() == "1"
    auth_local = os.environ.get("NEXUS_LOCAL_MODEL_CALL_ALLOWED", "").strip() == "1"
    live = (
        "AUTHORIZED_CANARY_REQUIRED"
        if (auth_ext or auth_local)
        else "BLOCKED_EXTERNAL_AUTH"
    )

    receipt: dict[str, Any] = {
        "schema": "nexus.all_capability_closure_receipt.v1",
        "baseline_head": subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=root, text=True
        ).strip(),
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "planner_contract_count": 57,
        "promotable_count": len(promotable),
        "default_real_count": ec_counts.get("DEFAULT_REAL", 0),
        "triggered_real_count": ec_counts.get("TRIGGERED_REAL", 0),
        "stage_owned_real_count": ec_counts.get("STAGE_OWNED_REAL", 0),
        "external_auth_required_count": ec_counts.get("EXTERNAL_AUTH_REQUIRED", 0),
        "control_plane_count": ec_counts.get("CONTROL_PLANE_REFERENCE", 0),
        "experimental_count": ec_counts.get("EXPERIMENTAL_NOT_PROMOTED", 0),
        "alias_count": ec_counts.get("LEGACY_ALIAS", 0),
        "missing_engine_count": ec_counts.get("MISSING_ENGINE", 0),
        "promotable_missing_engine_count": len(prom_missing),
        "probe_only_success_count": probe_only,
        "fixture_callable_count": fixture_count,
        "real_positive_fail_count": real_positive_fails,
        "routing_surface_changed": False,
        "public_claim_allowed": False,
        "catalog_denominators": {
            "union": catalog.get("canonical_union_count"),
            "canonical": catalog.get("canonical_row_count"),
            "alias": catalog.get("alias_row_count"),
            "planner": catalog.get("planner_node_count"),
        },
        "execution_class_counts": dict(ec_counts),
        "local_online_projection": {
            "planner_contract_count": 57,
            "independent_local_truth": False,
            "modes": {
                n: {
                    "local": project_local_execution_mode(n),
                    "online": project_online_execution_mode(n),
                }
                for n in list_planner_capability_names()
            },
        },
        "per_capability": per_cap,
        "blockers": blockers,
        "structural_blockers": structural_blockers,
        "semantic_blockers": semantic_blockers,
        "structural_closure": structural,
        "semantic_closure": semantic,
        "auth_blocked_count": sum(
            1 for row in per_cap if row["final_status"] == "AUTH_BLOCKED"
        ),
        "not_exercised_offline_count": sum(
            1
            for row in per_cap
            if row["final_status"] == "NOT_EXERCISED_OFFLINE"
        ),
        "live_provider_closure": live,
        "live_online_complete": False,
        "live_local_complete": False,
    }
    try:
        from nexus.services.capability_registry import build_wiring_matrix

        wm = build_wiring_matrix()
    except Exception:
        wm = {
            "node_count": 57,
            "contract_count": 57,
            "physical_runtime_eligible": 0,
            "execution_class_counts": dict(ec_counts),
            "routing_surface_changed": False,
        }
    if not isinstance(wm, dict):
        wm = {}
    wm = dict(wm)
    wm.setdefault("node_count", 57)
    wm.setdefault("contract_count", 57)
    wm.setdefault("execution_class_counts", dict(ec_counts))
    wm["routing_surface_changed"] = False
    # Physical target = formal REAL execution classes (DEFAULT+STAGE+TRIGGERED = 34)
    physical_target = sum(
        1
        for c in PLANNER_EXECUTION_CONTRACTS.values()
        if c.get("execution_class") in REAL_EXECUTION_CLASSES
    )
    # Observed = true positive real executions (not fixture/probe/auth-blocked/selected-only)
    observed_exec = 0
    for row in per_cap:
        if row.get("execution_class") not in REAL_EXECUTION_CLASSES:
            continue
        pos = row.get("positive") or {}
        status = str(row.get("final_status") or "")
        if status in {"AUTH_BLOCKED", "NOT_EXERCISED_OFFLINE", "OPERATIONAL_BLOCKED"}:
            continue
        if status in {"PROBE", "IMPLEMENTATION_FAILURE", "FAIL"}:
            continue
        phys = str(pos.get("physical_callable") or "")
        if "fixture" in phys.lower() or phys.startswith("test:"):
            continue
        if pos.get("action") in _SHALLOW_ACTIONS:
            continue
        if not pos.get("invoked"):
            continue
        if pos.get("skipped"):
            continue
        if status == "OK" or (pos.get("invoked") and pos.get("gate_passed") and not pos.get("skipped")):
            observed_exec += 1
    wm["physical_target_count"] = physical_target
    wm["physical_runtime_eligible"] = physical_target
    wm["physical_observed_execution_count"] = observed_exec
    receipt["physical_target_count"] = physical_target
    receipt["physical_observed_execution_count"] = observed_exec
    coverage_audit = audit_product_receipt_coverage(
        wiring_matrix=wm,
        live_local_complete=False,
        live_online_complete=False,
        semantic_closure=bool(semantic),
    )
    receipt["contract_declared_coverage"] = coverage_audit.get("contract_declared_coverage")
    receipt["observed_receipt_embed_coverage"] = coverage_audit.get(
        "observed_receipt_embed_coverage"
    )
    receipt["physical_contract_eligible_coverage"] = coverage_audit.get(
        "physical_contract_eligible_coverage"
    )
    receipt["physical_observed_execution_coverage"] = coverage_audit.get(
        "physical_observed_execution_coverage"
    )
    receipt["live_semantic_coverage"] = coverage_audit.get("live_semantic_coverage")
    receipt["all_closure_complete"] = bool(coverage_audit.get("all_closure_complete"))
    receipt["coverage_audit"] = {
        k: coverage_audit.get(k)
        for k in (
            "contract_declared_coverage",
            "observed_receipt_embed_coverage",
            "physical_contract_eligible_coverage",
            "physical_observed_execution_coverage",
            "live_semantic_coverage",
            "all_closure_complete",
            "embed_complete",
            "public_claim_allowed",
        )
    }
    receipt["public_claim_allowed"] = False
    text = json.dumps(receipt, indent=2, ensure_ascii=False) + "\n"
    RECEIPT_PATH.write_text(text, encoding="utf-8")
    RECEIPT_TMP.write_text(text, encoding="utf-8")
    return receipt


def test_generate_closure_receipt_required() -> None:
    """Receipt generation is mandatory — suite fails closed if generation fails."""
    receipt = build_and_write_closure_receipt()
    assert RECEIPT_PATH.is_file()
    assert RECEIPT_TMP.is_file()
    assert receipt["planner_contract_count"] == 57
    assert receipt["promotable_count"] == 53
    assert receipt["promotable_missing_engine_count"] == 0
    assert receipt["probe_only_success_count"] == 0
    assert receipt["fixture_callable_count"] == 0
    assert receipt["routing_surface_changed"] is False
    assert receipt["public_claim_allowed"] is False
    assert receipt["structural_closure"] is True, receipt.get("blockers", [])[:10]
    assert int(receipt.get("physical_target_count") or 0) == 34
    phys = receipt.get("physical_observed_execution_coverage") or {}
    assert int(phys.get("physical_target") or 0) == 34
    assert receipt.get("all_closure_complete") is False
    # Offline structural closure must not hide missing implementations.
    real_structural_blockers = [
        b
        for b in receipt["structural_blockers"]
        if b.get("promotable") and b.get("execution_class") in REAL_EXECUTION_CLASSES
    ]
    assert real_structural_blockers == [], real_structural_blockers[:8]
    assert receipt["semantic_closure"] is False
    assert receipt["live_online_complete"] is False
    assert receipt["live_local_complete"] is False


def test_family_canary_selection_authority_is_production_planner() -> None:
    result = _run_family_canary("codeintel", positive=True)

    assert result["selection_authority"] == "CapabilityPlanner"
    assert result["planner_selected"] is True
    assert result["planner_decision_id"]


def test_family_canary_online_edge_is_registered_and_fail_closed_without_auth() -> None:
    result = _run_family_canary("codeintel", positive=True)

    assert result["online_provider"] != "fixture"
    assert result["online_provider_call_count"] == 0
    assert result["online_gate_passed"] is False


def test_family_canary_verifier_executes_real_isolated_command() -> None:
    result = _run_family_canary("codeintel", positive=True)

    assert result["verifier_physical_callable"].endswith("run_isolated_verifier")
    assert result["verifier_exit_code"] == 0
    assert result["verifier_status"] == "pass"
    assert result["verifier_artifact"].startswith("sha256:")


def test_authorized_local_exception_cannot_be_promoted_to_live_ok(tmp_path: Path) -> None:
    response = {
        "provider": "ollama",
        "physical_callable": "LocalModelExecutor.run",
        "local_model_invoked": True,
        "output_delivered": True,
        "fallback_reason": "local_assist_exception:artifact_root_ephemeral",
        "candidate_summary": {
            "isolation_status": "isolated",
            "selected_candidate_hash_matches_applied": True,
            "selected_candidate_hash": "a" * 64,
            "applied_patch_hash": "a" * 64,
        },
        "verifier_summary": {"verifier_reached": True, "verifier_status": "pass"},
        "receipt_path": str(tmp_path / "missing-receipt.json"),
    }
    assert _local_live_proof_complete(
        name="local_model_executor",
        auth_local=True,
        invoked=True,
        skipped=False,
        gate=True,
        local_stage={"status": "SUCCEEDED", "reason": ""},
        local_response=response,
        physical_callable="local_stage:LocalModelExecutor",
    ) is False


def test_family_canary_reads_production_executor_outcome_not_wrapper_shell() -> None:
    result = _run_family_canary("codeintel", positive=True)

    assert result["action"] == "lookup_implementation"
    assert result["semantic_status"] == "SUCCEEDED"
    assert result["contract_violations"] == []


@pytest.mark.parametrize("name", _promotable_names())
def test_promotable_family_canary_mainchain_entry(name: str) -> None:
    """Each promotable node: pos+neg via MainchainEntry path, consumer proof, no false green."""
    pos = _run_family_canary(name, positive=True)
    neg = _run_family_canary(name, positive=False)
    contract = PLANNER_EXECUTION_CONTRACTS[name]
    assert pos["mainchain_entry"] is True
    assert pos["planner_selected"] is True
    assert pos["public_claim_allowed"] is False
    auth_local = os.environ.get("NEXUS_LOCAL_MODEL_CALL_ALLOWED", "").strip() == "1"
    auth_ext = os.environ.get("NEXUS_EXTERNAL_RUNTIME_AUTHORIZED", "").strip() == "1"
    if name in {"claim_gate", "delivery_gate"}:
        # Offline: NOT_EXERCISED; with external auth: OK if postflight real, else honest FAIL
        if auth_ext:
            expected_positive_statuses = {"OK", "FAIL", "NOT_EXERCISED_OFFLINE"}
        else:
            expected_positive_statuses = {"NOT_EXERCISED_OFFLINE"}
    elif name == "learn_scheduler":
        expected_positive_statuses = {"OPERATIONAL_BLOCKED", "OK"}
    elif contract.get("provider_authorization_required"):
        if name in LOCAL_STAGE_CAPABILITIES and auth_local:
            # Authorized local live: real Ollama success → OK; residual fail stays honest
            expected_positive_statuses = {"OK", "FAIL", "IMPLEMENTATION_FAILURE", "AUTH_BLOCKED"}
        elif auth_ext:
            # Live authorized: OK when real; OPERATIONAL/AUTH residual honest; no silent green
            expected_positive_statuses = {
                "OK",
                "AUTH_BLOCKED",
                "OPERATIONAL_BLOCKED",
                "FAIL",
                "IMPLEMENTATION_FAILURE",
                "NOT_EXERCISED_OFFLINE",
            }
        else:
            expected_positive_statuses = {"AUTH_BLOCKED"}
    else:
        expected_positive_statuses = {"OK"}
    assert pos["final_status"] in expected_positive_statuses, (
        name,
        pos["first_broken_edge"],
        pos,
    )
    assert neg["final_status"] == "OK", (name, neg["first_broken_edge"], neg)
    # Consumer proof present for non-NONE effects
    if contract["consumer_effect"] != "NONE" and pos["final_status"] == "OK":
        assert pos["consumer_proof"].get("kind")
        if contract["consumer_effect"] == "PROMPT_EVIDENCE":
            assert pos["consumer_proof"].get("evidence_refs_present") or pos[
                "consumer_proof"
            ].get("prompt_marker_or_payload")
        if contract["consumer_effect"] == "POSTFLIGHT_GATE":
            assert pos["consumer_proof"].get("gate_receipt")
        if contract["consumer_effect"] == "EXECUTION_CONTROL":
            assert pos["consumer_proof"].get("control_receipt")
    # REAL requires physical invoke + evidence on positive
    if contract["execution_class"] in REAL_EXECUTION_CLASSES and pos["final_status"] == "OK":
        assert pos["invoked"] is True and pos["skipped"] is False
        assert pos["physical_callable"]
        assert pos["evidence_refs"] or pos["action"]
        assert pos["action"] not in _SHALLOW_ACTIONS or pos["gate_passed"] is not True
    if pos["final_status"] == "AUTH_BLOCKED" and name not in LOCAL_STAGE_CAPABILITIES:
        assert pos["invoked"] is True
        assert pos["skipped"] is False
        assert pos["gate_passed"] is False
        assert pos["action"] == "auth_gate"
        assert pos["semantic_status"] == "BLOCKED"
        assert pos["outcome_auth_required"] is True
        assert pos["outcome_error"].startswith("BLOCKED_EXTERNAL_AUTH")
        assert pos["evidence_refs"]
        assert pos["outcome_contributed"] is False
    if pos["final_status"] == "AUTH_BLOCKED" and name in LOCAL_STAGE_CAPABILITIES:
        assert pos["local_provider"] == "ollama"
        assert pos["local_fallback_reason"] == "provider_not_configured"
        assert pos["local_stage_status"] in {"BLOCKED", "FAILED", "NOT_RUN"}
        assert pos["gate_passed"] is False
    if pos["final_status"] == "NOT_EXERCISED_OFFLINE":
        assert pos["gate_passed"] is False
        assert "blocker:online_not_invoked" in pos["evidence_refs"]
        assert pos["action"] != "auth_gate"
    # EXTERNAL_AUTH: must not probe-success without auth
    if contract["execution_class"] == EXECUTION_CLASS_EXTERNAL_AUTH_REQUIRED:
        if pos["gate_passed"] is True:
            assert pos["action"] not in _SHALLOW_ACTIONS
    # Negative false-green: must not claim success with empty evidence for REAL
    if contract["execution_class"] in REAL_EXECUTION_CLASSES:
        if neg["gate_passed"] is True and neg["invoked"] is True:
            assert neg["status"] != "SUCCEEDED" or neg["evidence_refs"] or neg["skipped"]
