from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping


HARD_GATE_COMPATIBILITY_SCHEMA = "nexus.hard_gate_compatibility.v1"
PASS_LIKE = {"PASS", "NOT_APPLICABLE"}


@dataclass(frozen=True)
class HardGateCompatibility:
    route_context_changed: bool = False
    route_hardened: bool = False
    mfp_confidence_min: float = 0.98
    router_acceptance_status: str = "NOT_APPLICABLE"
    closeout_claim: bool = False
    completion_status: str = "NOT_APPLICABLE"
    context_sources_dropped: bool = False
    hallucination_guard_status: str = "NOT_APPLICABLE"
    mutation_assurance_required: bool = False
    mutation_assurance_status: str = "NOT_APPLICABLE"
    bdd_acceptance_required: bool = False
    bdd_preflight_status: str = "NOT_APPLICABLE"
    capability_contract_type: str = "NOT_APPLICABLE"
    pre_model_rescue_planned: bool = False
    skill_tier_status: str = "NOT_APPLICABLE"
    quarantined_skill_detected: bool = False
    research_supply_gap: bool = False
    live_benchmark_requested: bool = False
    forced_swarm: bool = False
    parallel_slot_planned: bool = False
    jit_symbol_drift_detected: bool = False
    ast_graph_freshness_status: str = "NOT_APPLICABLE"
    phase_token_sentinel_status: str = "NOT_APPLICABLE"
    retry_pollution_detected: bool = False
    retry_pollution_isolated: bool = True
    memory_sanitizer_status: str = "NOT_APPLICABLE"
    private_leak_detected: bool = False
    dirty_worktree: bool = False
    spec_kit_init_requested: bool = False
    transient_output_root_status: str = "NOT_APPLICABLE"
    rationale_required: bool = False
    rationale_status: str = "NOT_APPLICABLE"
    autogenerated_rationale_noise_detected: bool = False
    evidence_union_merge_required: bool = False
    union_merge_driver_status: str = "NOT_APPLICABLE"
    union_merge_cap_status: str = "NOT_APPLICABLE"
    union_merge_schema_status: str = "NOT_APPLICABLE"
    context_pack_security_required: bool = False
    context_pack_security_status: str = "NOT_APPLICABLE"
    suspicious_diff_or_log_included: bool = False
    remote_config_trust_status: str = "NOT_APPLICABLE"
    evidence_seal_required: bool = False
    evidence_seal_status: str = "NOT_APPLICABLE"
    evidence_hash_status: str = "NOT_APPLICABLE"
    partial_telemetry_detected: bool = False
    network_fetch_required: bool = False
    network_fetch_guard_status: str = "NOT_APPLICABLE"
    redirect_revalidation_status: str = "NOT_APPLICABLE"
    private_network_target_detected: bool = False
    graph_integrity_required: bool = False
    entity_namespace_status: str = "NOT_APPLICABLE"
    dangling_edge_detected: bool = False
    dedup_guard_required: bool = False
    dedup_precision_status: str = "NOT_APPLICABLE"
    low_entropy_merge_detected: bool = False
    runtime_update_allowed: bool = False
    public_benchmark_allowed: bool = False
    evidence_refs: tuple[str, ...] = ()
    schema: str = HARD_GATE_COMPATIBILITY_SCHEMA

    def to_dict(self) -> dict[str, Any]:
        payload = {
            "schema": self.schema,
            "route_context_changed": self.route_context_changed,
            "route_hardened": self.route_hardened,
            "mfp_confidence_min": self.mfp_confidence_min,
            "router_acceptance_status": _status(self.router_acceptance_status),
            "closeout_claim": self.closeout_claim,
            "completion_status": _status(self.completion_status),
            "context_sources_dropped": self.context_sources_dropped,
            "hallucination_guard_status": _status(self.hallucination_guard_status),
            "mutation_assurance_required": self.mutation_assurance_required,
            "mutation_assurance_status": _status(self.mutation_assurance_status),
            "bdd_acceptance_required": self.bdd_acceptance_required,
            "bdd_preflight_status": _status(self.bdd_preflight_status),
            "capability_contract_type": _contract_type(self.capability_contract_type),
            "pre_model_rescue_planned": self.pre_model_rescue_planned,
            "skill_tier_status": _status(self.skill_tier_status),
            "quarantined_skill_detected": self.quarantined_skill_detected,
            "research_supply_gap": self.research_supply_gap,
            "live_benchmark_requested": self.live_benchmark_requested,
            "forced_swarm": self.forced_swarm,
            "parallel_slot_planned": self.parallel_slot_planned,
            "jit_symbol_drift_detected": self.jit_symbol_drift_detected,
            "ast_graph_freshness_status": _status(self.ast_graph_freshness_status),
            "phase_token_sentinel_status": _status(self.phase_token_sentinel_status),
            "retry_pollution_detected": self.retry_pollution_detected,
            "retry_pollution_isolated": self.retry_pollution_isolated,
            "memory_sanitizer_status": _status(self.memory_sanitizer_status),
            "private_leak_detected": self.private_leak_detected,
            "dirty_worktree": self.dirty_worktree,
            "spec_kit_init_requested": self.spec_kit_init_requested,
            "transient_output_root_status": _status(self.transient_output_root_status),
            "rationale_required": self.rationale_required,
            "rationale_status": _status(self.rationale_status),
            "autogenerated_rationale_noise_detected": self.autogenerated_rationale_noise_detected,
            "evidence_union_merge_required": self.evidence_union_merge_required,
            "union_merge_driver_status": _status(self.union_merge_driver_status),
            "union_merge_cap_status": _status(self.union_merge_cap_status),
            "union_merge_schema_status": _status(self.union_merge_schema_status),
            "context_pack_security_required": self.context_pack_security_required,
            "context_pack_security_status": _status(self.context_pack_security_status),
            "suspicious_diff_or_log_included": self.suspicious_diff_or_log_included,
            "remote_config_trust_status": _status(self.remote_config_trust_status),
            "evidence_seal_required": self.evidence_seal_required,
            "evidence_seal_status": _status(self.evidence_seal_status),
            "evidence_hash_status": _status(self.evidence_hash_status),
            "partial_telemetry_detected": self.partial_telemetry_detected,
            "network_fetch_required": self.network_fetch_required,
            "network_fetch_guard_status": _status(self.network_fetch_guard_status),
            "redirect_revalidation_status": _status(self.redirect_revalidation_status),
            "private_network_target_detected": self.private_network_target_detected,
            "graph_integrity_required": self.graph_integrity_required,
            "entity_namespace_status": _status(self.entity_namespace_status),
            "dangling_edge_detected": self.dangling_edge_detected,
            "dedup_guard_required": self.dedup_guard_required,
            "dedup_precision_status": _status(self.dedup_precision_status),
            "low_entropy_merge_detected": self.low_entropy_merge_detected,
            "runtime_update_allowed": self.runtime_update_allowed,
            "public_benchmark_allowed": self.public_benchmark_allowed,
            "evidence_refs": list(self.evidence_refs),
            "claim_boundary": [
                "This compatibility contract checks existing hard gates before optimization work.",
                "It does not approve runtime updates or public benchmark claims.",
            ],
        }
        payload["blockers"] = validate_hard_gate_compatibility(payload)
        payload["status"] = "PASS" if not payload["blockers"] else "RETURN"
        return payload


def build_hard_gate_compatibility(
    *,
    route_context_changed: bool = False,
    route_hardened: bool = False,
    mfp_confidence_min: float = 0.98,
    router_acceptance_status: str = "NOT_APPLICABLE",
    closeout_claim: bool = False,
    completion_status: str = "NOT_APPLICABLE",
    context_sources_dropped: bool = False,
    hallucination_guard_status: str = "NOT_APPLICABLE",
    mutation_assurance_required: bool = False,
    mutation_assurance_status: str = "NOT_APPLICABLE",
    bdd_acceptance_required: bool = False,
    bdd_preflight_status: str = "NOT_APPLICABLE",
    capability_contract_type: str = "NOT_APPLICABLE",
    pre_model_rescue_planned: bool = False,
    skill_tier_status: str = "NOT_APPLICABLE",
    quarantined_skill_detected: bool = False,
    research_supply_gap: bool = False,
    live_benchmark_requested: bool = False,
    forced_swarm: bool = False,
    parallel_slot_planned: bool = False,
    jit_symbol_drift_detected: bool = False,
    ast_graph_freshness_status: str = "NOT_APPLICABLE",
    phase_token_sentinel_status: str = "NOT_APPLICABLE",
    retry_pollution_detected: bool = False,
    retry_pollution_isolated: bool = True,
    memory_sanitizer_status: str = "NOT_APPLICABLE",
    private_leak_detected: bool = False,
    dirty_worktree: bool = False,
    spec_kit_init_requested: bool = False,
    transient_output_root_status: str = "NOT_APPLICABLE",
    rationale_required: bool = False,
    rationale_status: str = "NOT_APPLICABLE",
    autogenerated_rationale_noise_detected: bool = False,
    evidence_union_merge_required: bool = False,
    union_merge_driver_status: str = "NOT_APPLICABLE",
    union_merge_cap_status: str = "NOT_APPLICABLE",
    union_merge_schema_status: str = "NOT_APPLICABLE",
    context_pack_security_required: bool = False,
    context_pack_security_status: str = "NOT_APPLICABLE",
    suspicious_diff_or_log_included: bool = False,
    remote_config_trust_status: str = "NOT_APPLICABLE",
    evidence_seal_required: bool = False,
    evidence_seal_status: str = "NOT_APPLICABLE",
    evidence_hash_status: str = "NOT_APPLICABLE",
    partial_telemetry_detected: bool = False,
    network_fetch_required: bool = False,
    network_fetch_guard_status: str = "NOT_APPLICABLE",
    redirect_revalidation_status: str = "NOT_APPLICABLE",
    private_network_target_detected: bool = False,
    graph_integrity_required: bool = False,
    entity_namespace_status: str = "NOT_APPLICABLE",
    dangling_edge_detected: bool = False,
    dedup_guard_required: bool = False,
    dedup_precision_status: str = "NOT_APPLICABLE",
    low_entropy_merge_detected: bool = False,
    runtime_update_allowed: bool = False,
    public_benchmark_allowed: bool = False,
    evidence_refs: list[str] | tuple[str, ...] = (),
) -> dict[str, Any]:
    return HardGateCompatibility(
        route_context_changed=bool(route_context_changed),
        route_hardened=bool(route_hardened),
        mfp_confidence_min=float(mfp_confidence_min),
        router_acceptance_status=router_acceptance_status,
        closeout_claim=bool(closeout_claim),
        completion_status=completion_status,
        context_sources_dropped=bool(context_sources_dropped),
        hallucination_guard_status=hallucination_guard_status,
        mutation_assurance_required=bool(mutation_assurance_required),
        mutation_assurance_status=mutation_assurance_status,
        bdd_acceptance_required=bool(bdd_acceptance_required),
        bdd_preflight_status=bdd_preflight_status,
        capability_contract_type=capability_contract_type,
        pre_model_rescue_planned=bool(pre_model_rescue_planned),
        skill_tier_status=skill_tier_status,
        quarantined_skill_detected=bool(quarantined_skill_detected),
        research_supply_gap=bool(research_supply_gap),
        live_benchmark_requested=bool(live_benchmark_requested),
        forced_swarm=bool(forced_swarm),
        parallel_slot_planned=bool(parallel_slot_planned),
        jit_symbol_drift_detected=bool(jit_symbol_drift_detected),
        ast_graph_freshness_status=ast_graph_freshness_status,
        phase_token_sentinel_status=phase_token_sentinel_status,
        retry_pollution_detected=bool(retry_pollution_detected),
        retry_pollution_isolated=bool(retry_pollution_isolated),
        memory_sanitizer_status=memory_sanitizer_status,
        private_leak_detected=bool(private_leak_detected),
        dirty_worktree=bool(dirty_worktree),
        spec_kit_init_requested=bool(spec_kit_init_requested),
        transient_output_root_status=transient_output_root_status,
        rationale_required=bool(rationale_required),
        rationale_status=rationale_status,
        autogenerated_rationale_noise_detected=bool(autogenerated_rationale_noise_detected),
        evidence_union_merge_required=bool(evidence_union_merge_required),
        union_merge_driver_status=union_merge_driver_status,
        union_merge_cap_status=union_merge_cap_status,
        union_merge_schema_status=union_merge_schema_status,
        context_pack_security_required=bool(context_pack_security_required),
        context_pack_security_status=context_pack_security_status,
        suspicious_diff_or_log_included=bool(suspicious_diff_or_log_included),
        remote_config_trust_status=remote_config_trust_status,
        evidence_seal_required=bool(evidence_seal_required),
        evidence_seal_status=evidence_seal_status,
        evidence_hash_status=evidence_hash_status,
        partial_telemetry_detected=bool(partial_telemetry_detected),
        network_fetch_required=bool(network_fetch_required),
        network_fetch_guard_status=network_fetch_guard_status,
        redirect_revalidation_status=redirect_revalidation_status,
        private_network_target_detected=bool(private_network_target_detected),
        graph_integrity_required=bool(graph_integrity_required),
        entity_namespace_status=entity_namespace_status,
        dangling_edge_detected=bool(dangling_edge_detected),
        dedup_guard_required=bool(dedup_guard_required),
        dedup_precision_status=dedup_precision_status,
        low_entropy_merge_detected=bool(low_entropy_merge_detected),
        runtime_update_allowed=bool(runtime_update_allowed),
        public_benchmark_allowed=bool(public_benchmark_allowed),
        evidence_refs=tuple(str(item) for item in evidence_refs if str(item).strip()),
    ).to_dict()


def validate_hard_gate_compatibility(payload: Mapping[str, Any]) -> list[str]:
    blockers: list[str] = []
    if bool(payload.get("runtime_update_allowed", False)):
        blockers.append("compatibility_contract_must_not_update_runtime")
    if bool(payload.get("public_benchmark_allowed", False)):
        blockers.append("compatibility_contract_must_not_unlock_public_benchmark")
    if bool(payload.get("route_context_changed", False)):
        if not bool(payload.get("route_hardened", False)):
            blockers.append("hardened_router_not_enabled")
        if _status(payload.get("router_acceptance_status")) != "PASS":
            blockers.append("router_acceptance_not_pass")
        if _as_float(payload.get("mfp_confidence_min")) <= 0:
            blockers.append("invalid_mfp_confidence_min")
    if bool(payload.get("closeout_claim", False)) and _status(payload.get("completion_status")) != "PASS":
        blockers.append("completion_envelope_not_pass")
    if bool(payload.get("context_sources_dropped", False)):
        if _status(payload.get("hallucination_guard_status")) != "PASS":
            blockers.append("hallucination_guard_not_pass")
    if bool(payload.get("mutation_assurance_required", False)):
        if _status(payload.get("mutation_assurance_status")) != "PASS":
            blockers.append("mutation_assurance_not_pass")
    if bool(payload.get("bdd_acceptance_required", False)):
        if _status(payload.get("bdd_preflight_status")) != "PASS":
            blockers.append("bdd_preflight_not_pass")
    if _contract_type(payload.get("capability_contract_type")) == "required":
        if bool(payload.get("pre_model_rescue_planned", False)):
            blockers.append("required_capability_pre_model_rescue_planned")
    if bool(payload.get("quarantined_skill_detected", False)):
        blockers.append("quarantined_skill_detected")
    if _status(payload.get("skill_tier_status")) not in PASS_LIKE:
        blockers.append("skill_tier_status_not_pass")
    if bool(payload.get("research_supply_gap", False)) and bool(payload.get("live_benchmark_requested", False)):
        blockers.append("research_supply_gap_blocks_live_benchmark")
    if bool(payload.get("forced_swarm", False)) and bool(payload.get("parallel_slot_planned", False)):
        blockers.append("forced_swarm_must_be_serialized")
    if bool(payload.get("jit_symbol_drift_detected", False)):
        if _status(payload.get("ast_graph_freshness_status")) != "PASS":
            blockers.append("ast_graph_not_fresh")
    if _status(payload.get("phase_token_sentinel_status")) not in PASS_LIKE:
        blockers.append("phase_token_sentinel_not_pass")
    if bool(payload.get("retry_pollution_detected", False)) and not bool(payload.get("retry_pollution_isolated", False)):
        blockers.append("retry_pollution_not_isolated")
    if bool(payload.get("private_leak_detected", False)):
        blockers.append("private_leak_detected")
    if _status(payload.get("memory_sanitizer_status")) not in PASS_LIKE:
        blockers.append("memory_sanitizer_not_pass")
    if bool(payload.get("dirty_worktree", False)) and bool(payload.get("spec_kit_init_requested", False)):
        blockers.append("dirty_worktree_blocks_spec_kit")
    if _status(payload.get("transient_output_root_status")) not in PASS_LIKE:
        blockers.append("transient_output_root_not_pass")
    if bool(payload.get("rationale_required", False)):
        if _status(payload.get("rationale_status")) != "PASS":
            blockers.append("rationale_context_not_pass")
    if bool(payload.get("autogenerated_rationale_noise_detected", False)):
        blockers.append("autogenerated_rationale_noise_detected")
    if bool(payload.get("evidence_union_merge_required", False)):
        if _status(payload.get("union_merge_driver_status")) != "PASS":
            blockers.append("union_merge_driver_not_pass")
        if _status(payload.get("union_merge_cap_status")) != "PASS":
            blockers.append("union_merge_cap_not_pass")
        if _status(payload.get("union_merge_schema_status")) != "PASS":
            blockers.append("union_merge_schema_not_pass")
    if bool(payload.get("context_pack_security_required", False)):
        if _status(payload.get("context_pack_security_status")) != "PASS":
            blockers.append("context_pack_security_not_pass")
    if bool(payload.get("suspicious_diff_or_log_included", False)):
        blockers.append("suspicious_diff_or_log_included")
    if _status(payload.get("remote_config_trust_status")) not in PASS_LIKE:
        blockers.append("remote_config_trust_not_pass")
    if bool(payload.get("evidence_seal_required", False)):
        if _status(payload.get("evidence_seal_status")) != "PASS":
            blockers.append("evidence_seal_not_pass")
        if _status(payload.get("evidence_hash_status")) != "PASS":
            blockers.append("evidence_hash_not_pass")
    if bool(payload.get("partial_telemetry_detected", False)):
        blockers.append("partial_telemetry_detected")
    if bool(payload.get("network_fetch_required", False)):
        if _status(payload.get("network_fetch_guard_status")) != "PASS":
            blockers.append("network_fetch_guard_not_pass")
        if _status(payload.get("redirect_revalidation_status")) != "PASS":
            blockers.append("redirect_revalidation_not_pass")
    if bool(payload.get("private_network_target_detected", False)):
        blockers.append("private_network_target_detected")
    if bool(payload.get("graph_integrity_required", False)):
        if _status(payload.get("entity_namespace_status")) != "PASS":
            blockers.append("entity_namespace_not_pass")
    if bool(payload.get("dangling_edge_detected", False)):
        blockers.append("dangling_edge_detected")
    if bool(payload.get("dedup_guard_required", False)):
        if _status(payload.get("dedup_precision_status")) != "PASS":
            blockers.append("dedup_precision_not_pass")
    if bool(payload.get("low_entropy_merge_detected", False)):
        blockers.append("low_entropy_merge_detected")
    return sorted(set(blockers))


def _status(value: Any) -> str:
    return str(value or "NOT_APPLICABLE").strip().upper()


def _contract_type(value: Any) -> str:
    return str(value or "NOT_APPLICABLE").strip().lower()


def _as_float(value: Any) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0
