// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: federation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoverPeersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClusterId       string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	FederationToken string                 `protobuf:"bytes,2,opt,name=federation_token,json=federationToken,proto3" json:"federation_token,omitempty"`
	ManagerEndpoint string                 `protobuf:"bytes,3,opt,name=manager_endpoint,json=managerEndpoint,proto3" json:"manager_endpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiscoverPeersRequest) Reset() {
	*x = DiscoverPeersRequest{}
	mi := &file_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverPeersRequest) ProtoMessage() {}

func (x *DiscoverPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverPeersRequest.ProtoReflect.Descriptor instead.
func (*DiscoverPeersRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoverPeersRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *DiscoverPeersRequest) GetFederationToken() string {
	if x != nil {
		return x.FederationToken
	}
	return ""
}

func (x *DiscoverPeersRequest) GetManagerEndpoint() string {
	if x != nil {
		return x.ManagerEndpoint
	}
	return ""
}

type PeerInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterId         string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Region            string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	ManagerEndpoint   string                 `protobuf:"bytes,3,opt,name=manager_endpoint,json=managerEndpoint,proto3" json:"manager_endpoint,omitempty"`
	TotalCapacity     int64                  `protobuf:"varint,4,opt,name=total_capacity,json=totalCapacity,proto3" json:"total_capacity,omitempty"`
	AvailableCapacity int64                  `protobuf:"varint,5,opt,name=available_capacity,json=availableCapacity,proto3" json:"available_capacity,omitempty"`
	LeaderStatus      string                 `protobuf:"bytes,6,opt,name=leader_status,json=leaderStatus,proto3" json:"leader_status,omitempty"` // LEADER / FOLLOWER / CANDIDATE
	LastSeen          int64                  `protobuf:"varint,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{1}
}

func (x *PeerInfo) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *PeerInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PeerInfo) GetManagerEndpoint() string {
	if x != nil {
		return x.ManagerEndpoint
	}
	return ""
}

func (x *PeerInfo) GetTotalCapacity() int64 {
	if x != nil {
		return x.TotalCapacity
	}
	return 0
}

func (x *PeerInfo) GetAvailableCapacity() int64 {
	if x != nil {
		return x.AvailableCapacity
	}
	return 0
}

func (x *PeerInfo) GetLeaderStatus() string {
	if x != nil {
		return x.LeaderStatus
	}
	return ""
}

func (x *PeerInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type DiscoverPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	MyClusterId   string                 `protobuf:"bytes,2,opt,name=my_cluster_id,json=myClusterId,proto3" json:"my_cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverPeersResponse) Reset() {
	*x = DiscoverPeersResponse{}
	mi := &file_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverPeersResponse) ProtoMessage() {}

func (x *DiscoverPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverPeersResponse.ProtoReflect.Descriptor instead.
func (*DiscoverPeersResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoverPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *DiscoverPeersResponse) GetMyClusterId() string {
	if x != nil {
		return x.MyClusterId
	}
	return ""
}

type HeartbeatFederationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterId         string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Region            string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	TotalCapacity     int64                  `protobuf:"varint,3,opt,name=total_capacity,json=totalCapacity,proto3" json:"total_capacity,omitempty"`
	AvailableCapacity int64                  `protobuf:"varint,4,opt,name=available_capacity,json=availableCapacity,proto3" json:"available_capacity,omitempty"`
	Traceparent       string                 `protobuf:"bytes,5,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatFederationRequest) Reset() {
	*x = HeartbeatFederationRequest{}
	mi := &file_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatFederationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatFederationRequest) ProtoMessage() {}

func (x *HeartbeatFederationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatFederationRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatFederationRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatFederationRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *HeartbeatFederationRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *HeartbeatFederationRequest) GetTotalCapacity() int64 {
	if x != nil {
		return x.TotalCapacity
	}
	return 0
}

func (x *HeartbeatFederationRequest) GetAvailableCapacity() int64 {
	if x != nil {
		return x.AvailableCapacity
	}
	return 0
}

func (x *HeartbeatFederationRequest) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

type HeartbeatFederationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	LeaderCluster string                 `protobuf:"bytes,2,opt,name=leader_cluster,json=leaderCluster,proto3" json:"leader_cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatFederationResponse) Reset() {
	*x = HeartbeatFederationResponse{}
	mi := &file_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatFederationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatFederationResponse) ProtoMessage() {}

func (x *HeartbeatFederationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatFederationResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatFederationResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatFederationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatFederationResponse) GetLeaderCluster() string {
	if x != nil {
		return x.LeaderCluster
	}
	return ""
}

type RouteTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	DecisionId      string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	PreferredRegion string                 `protobuf:"bytes,3,opt,name=preferred_region,json=preferredRegion,proto3" json:"preferred_region,omitempty"`
	TaskPayload     []byte                 `protobuf:"bytes,4,opt,name=task_payload,json=taskPayload,proto3" json:"task_payload,omitempty"`
	Traceparent     string                 `protobuf:"bytes,5,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteTaskRequest) Reset() {
	*x = RouteTaskRequest{}
	mi := &file_federation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTaskRequest) ProtoMessage() {}

func (x *RouteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTaskRequest.ProtoReflect.Descriptor instead.
func (*RouteTaskRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{5}
}

func (x *RouteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RouteTaskRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *RouteTaskRequest) GetPreferredRegion() string {
	if x != nil {
		return x.PreferredRegion
	}
	return ""
}

func (x *RouteTaskRequest) GetTaskPayload() []byte {
	if x != nil {
		return x.TaskPayload
	}
	return nil
}

func (x *RouteTaskRequest) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

type RouteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routed        bool                   `protobuf:"varint,1,opt,name=routed,proto3" json:"routed,omitempty"`
	TargetCluster string                 `protobuf:"bytes,2,opt,name=target_cluster,json=targetCluster,proto3" json:"target_cluster,omitempty"`
	TargetNode    string                 `protobuf:"bytes,3,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTaskResponse) Reset() {
	*x = RouteTaskResponse{}
	mi := &file_federation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTaskResponse) ProtoMessage() {}

func (x *RouteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTaskResponse.ProtoReflect.Descriptor instead.
func (*RouteTaskResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{6}
}

func (x *RouteTaskResponse) GetRouted() bool {
	if x != nil {
		return x.Routed
	}
	return false
}

func (x *RouteTaskResponse) GetTargetCluster() string {
	if x != nil {
		return x.TargetCluster
	}
	return ""
}

func (x *RouteTaskResponse) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

type GlobalLeaderElectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Vote          []byte                 `protobuf:"bytes,3,opt,name=vote,proto3" json:"vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalLeaderElectionRequest) Reset() {
	*x = GlobalLeaderElectionRequest{}
	mi := &file_federation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalLeaderElectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalLeaderElectionRequest) ProtoMessage() {}

func (x *GlobalLeaderElectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalLeaderElectionRequest.ProtoReflect.Descriptor instead.
func (*GlobalLeaderElectionRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{7}
}

func (x *GlobalLeaderElectionRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *GlobalLeaderElectionRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *GlobalLeaderElectionRequest) GetVote() []byte {
	if x != nil {
		return x.Vote
	}
	return nil
}

type GlobalLeaderElectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	LeaderCluster string                 `protobuf:"bytes,3,opt,name=leader_cluster,json=leaderCluster,proto3" json:"leader_cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalLeaderElectionResponse) Reset() {
	*x = GlobalLeaderElectionResponse{}
	mi := &file_federation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalLeaderElectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalLeaderElectionResponse) ProtoMessage() {}

func (x *GlobalLeaderElectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalLeaderElectionResponse.ProtoReflect.Descriptor instead.
func (*GlobalLeaderElectionResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{8}
}

func (x *GlobalLeaderElectionResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *GlobalLeaderElectionResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *GlobalLeaderElectionResponse) GetLeaderCluster() string {
	if x != nil {
		return x.LeaderCluster
	}
	return ""
}

var File_federation_proto protoreflect.FileDescriptor

const file_federation_proto_rawDesc = "" +
	"\n" +
	"\x10federation.proto\x12\x19nexus.swarm.federation.v1\"\x8b\x01\n" +
	"\x14DiscoverPeersRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12)\n" +
	"\x10federation_token\x18\x02 \x01(\tR\x0ffederationToken\x12)\n" +
	"\x10manager_endpoint\x18\x03 \x01(\tR\x0fmanagerEndpoint\"\x84\x02\n" +
	"\bPeerInfo\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12)\n" +
	"\x10manager_endpoint\x18\x03 \x01(\tR\x0fmanagerEndpoint\x12%\n" +
	"\x0etotal_capacity\x18\x04 \x01(\x03R\rtotalCapacity\x12-\n" +
	"\x12available_capacity\x18\x05 \x01(\x03R\x11availableCapacity\x12#\n" +
	"\rleader_status\x18\x06 \x01(\tR\fleaderStatus\x12\x1b\n" +
	"\tlast_seen\x18\a \x01(\x03R\blastSeen\"v\n" +
	"\x15DiscoverPeersResponse\x129\n" +
	"\x05peers\x18\x01 \x03(\v2#.nexus.swarm.federation.v1.PeerInfoR\x05peers\x12\"\n" +
	"\rmy_cluster_id\x18\x02 \x01(\tR\vmyClusterId\"\xcb\x01\n" +
	"\x1aHeartbeatFederationRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12%\n" +
	"\x0etotal_capacity\x18\x03 \x01(\x03R\rtotalCapacity\x12-\n" +
	"\x12available_capacity\x18\x04 \x01(\x03R\x11availableCapacity\x12 \n" +
	"\vtraceparent\x18\x05 \x01(\tR\vtraceparent\"`\n" +
	"\x1bHeartbeatFederationResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12%\n" +
	"\x0eleader_cluster\x18\x02 \x01(\tR\rleaderCluster\"\xbc\x01\n" +
	"\x10RouteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x12)\n" +
	"\x10preferred_region\x18\x03 \x01(\tR\x0fpreferredRegion\x12!\n" +
	"\ftask_payload\x18\x04 \x01(\fR\vtaskPayload\x12 \n" +
	"\vtraceparent\x18\x05 \x01(\tR\vtraceparent\"s\n" +
	"\x11RouteTaskResponse\x12\x16\n" +
	"\x06routed\x18\x01 \x01(\bR\x06routed\x12%\n" +
	"\x0etarget_cluster\x18\x02 \x01(\tR\rtargetCluster\x12\x1f\n" +
	"\vtarget_node\x18\x03 \x01(\tR\n" +
	"targetNode\"d\n" +
	"\x1bGlobalLeaderElectionRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x12\n" +
	"\x04vote\x18\x03 \x01(\fR\x04vote\"|\n" +
	"\x1cGlobalLeaderElectionResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\x12%\n" +
	"\x0eleader_cluster\x18\x03 \x01(\tR\rleaderCluster2\xf9\x03\n" +
	"\n" +
	"Federation\x12r\n" +
	"\rDiscoverPeers\x12/.nexus.swarm.federation.v1.DiscoverPeersRequest\x1a0.nexus.swarm.federation.v1.DiscoverPeersResponse\x12\x84\x01\n" +
	"\x13HeartbeatFederation\x125.nexus.swarm.federation.v1.HeartbeatFederationRequest\x1a6.nexus.swarm.federation.v1.HeartbeatFederationResponse\x12f\n" +
	"\tRouteTask\x12+.nexus.swarm.federation.v1.RouteTaskRequest\x1a,.nexus.swarm.federation.v1.RouteTaskResponse\x12\x87\x01\n" +
	"\x14GlobalLeaderElection\x126.nexus.swarm.federation.v1.GlobalLeaderElectionRequest\x1a7.nexus.swarm.federation.v1.GlobalLeaderElectionResponseB\rZ\v./api/protob\x06proto3"

var (
	file_federation_proto_rawDescOnce sync.Once
	file_federation_proto_rawDescData []byte
)

func file_federation_proto_rawDescGZIP() []byte {
	file_federation_proto_rawDescOnce.Do(func() {
		file_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federation_proto_rawDesc), len(file_federation_proto_rawDesc)))
	})
	return file_federation_proto_rawDescData
}

var file_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_federation_proto_goTypes = []any{
	(*DiscoverPeersRequest)(nil),         // 0: nexus.swarm.federation.v1.DiscoverPeersRequest
	(*PeerInfo)(nil),                     // 1: nexus.swarm.federation.v1.PeerInfo
	(*DiscoverPeersResponse)(nil),        // 2: nexus.swarm.federation.v1.DiscoverPeersResponse
	(*HeartbeatFederationRequest)(nil),   // 3: nexus.swarm.federation.v1.HeartbeatFederationRequest
	(*HeartbeatFederationResponse)(nil),  // 4: nexus.swarm.federation.v1.HeartbeatFederationResponse
	(*RouteTaskRequest)(nil),             // 5: nexus.swarm.federation.v1.RouteTaskRequest
	(*RouteTaskResponse)(nil),            // 6: nexus.swarm.federation.v1.RouteTaskResponse
	(*GlobalLeaderElectionRequest)(nil),  // 7: nexus.swarm.federation.v1.GlobalLeaderElectionRequest
	(*GlobalLeaderElectionResponse)(nil), // 8: nexus.swarm.federation.v1.GlobalLeaderElectionResponse
}
var file_federation_proto_depIdxs = []int32{
	1, // 0: nexus.swarm.federation.v1.DiscoverPeersResponse.peers:type_name -> nexus.swarm.federation.v1.PeerInfo
	0, // 1: nexus.swarm.federation.v1.Federation.DiscoverPeers:input_type -> nexus.swarm.federation.v1.DiscoverPeersRequest
	3, // 2: nexus.swarm.federation.v1.Federation.HeartbeatFederation:input_type -> nexus.swarm.federation.v1.HeartbeatFederationRequest
	5, // 3: nexus.swarm.federation.v1.Federation.RouteTask:input_type -> nexus.swarm.federation.v1.RouteTaskRequest
	7, // 4: nexus.swarm.federation.v1.Federation.GlobalLeaderElection:input_type -> nexus.swarm.federation.v1.GlobalLeaderElectionRequest
	2, // 5: nexus.swarm.federation.v1.Federation.DiscoverPeers:output_type -> nexus.swarm.federation.v1.DiscoverPeersResponse
	4, // 6: nexus.swarm.federation.v1.Federation.HeartbeatFederation:output_type -> nexus.swarm.federation.v1.HeartbeatFederationResponse
	6, // 7: nexus.swarm.federation.v1.Federation.RouteTask:output_type -> nexus.swarm.federation.v1.RouteTaskResponse
	8, // 8: nexus.swarm.federation.v1.Federation.GlobalLeaderElection:output_type -> nexus.swarm.federation.v1.GlobalLeaderElectionResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_federation_proto_init() }
func file_federation_proto_init() {
	if File_federation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federation_proto_rawDesc), len(file_federation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_federation_proto_goTypes,
		DependencyIndexes: file_federation_proto_depIdxs,
		MessageInfos:      file_federation_proto_msgTypes,
	}.Build()
	File_federation_proto = out.File
	file_federation_proto_goTypes = nil
	file_federation_proto_depIdxs = nil
}
