// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: swarm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // e.g., ["rust-reflex", "ast-audit", "gpu-eval"]
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`             // "ONLINE", "BUSY", "MAINTENANCE"
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_swarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatReq) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HeartbeatReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	SyncTimestamp int64                  `protobuf:"varint,2,opt,name=sync_timestamp,json=syncTimestamp,proto3" json:"sync_timestamp,omitempty"`
	NextAction    string                 `protobuf:"bytes,3,opt,name=next_action,json=nextAction,proto3" json:"next_action,omitempty"` // e.g., "STANDBY", "FLUSH_CACHE"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	mi := &file_swarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResp) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatResp) GetSyncTimestamp() int64 {
	if x != nil {
		return x.SyncTimestamp
	}
	return 0
}

func (x *HeartbeatResp) GetNextAction() string {
	if x != nil {
		return x.NextAction
	}
	return ""
}

type SensingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	TaskType      string                 `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Traceparent   string                 `protobuf:"bytes,6,opt,name=traceparent,proto3" json:"traceparent,omitempty"` // W3C format
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`         // Optional: Code snippet or metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensingReq) Reset() {
	*x = SensingReq{}
	mi := &file_swarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensingReq) ProtoMessage() {}

func (x *SensingReq) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensingReq.ProtoReflect.Descriptor instead.
func (*SensingReq) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{2}
}

func (x *SensingReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SensingReq) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *SensingReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SensingReq) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *SensingReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SensingReq) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *SensingReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SensingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "PASS", "FAIL", "REJECT"
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Metrics       *Metrics               `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ResultsPatch  []byte                 `protobuf:"bytes,6,opt,name=results_patch,json=resultsPatch,proto3" json:"results_patch,omitempty"` // Optional: Suggested fix or patch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensingResp) Reset() {
	*x = SensingResp{}
	mi := &file_swarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensingResp) ProtoMessage() {}

func (x *SensingResp) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensingResp.ProtoReflect.Descriptor instead.
func (*SensingResp) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{3}
}

func (x *SensingResp) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SensingResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SensingResp) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SensingResp) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *SensingResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SensingResp) GetResultsPatch() []byte {
	if x != nil {
		return x.ResultsPatch
	}
	return nil
}

type Metrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SelectionLatencyUs int64                  `protobuf:"varint,1,opt,name=selection_latency_us,json=selectionLatencyUs,proto3" json:"selection_latency_us,omitempty"`
	NetworkLatencyMs   int64                  `protobuf:"varint,2,opt,name=network_latency_ms,json=networkLatencyMs,proto3" json:"network_latency_ms,omitempty"`
	ExecutionMs        int64                  `protobuf:"varint,3,opt,name=execution_ms,json=executionMs,proto3" json:"execution_ms,omitempty"`
	Region             string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	ConfidenceScore    float32                `protobuf:"fixed32,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_swarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{4}
}

func (x *Metrics) GetSelectionLatencyUs() int64 {
	if x != nil {
		return x.SelectionLatencyUs
	}
	return 0
}

func (x *Metrics) GetNetworkLatencyMs() int64 {
	if x != nil {
		return x.NetworkLatencyMs
	}
	return 0
}

func (x *Metrics) GetExecutionMs() int64 {
	if x != nil {
		return x.ExecutionMs
	}
	return 0
}

func (x *Metrics) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Metrics) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

var File_swarm_proto protoreflect.FileDescriptor

const file_swarm_proto_rawDesc = "" +
	"\n" +
	"\vswarm.proto\x12\x0enexus.swarm.v1\"\x81\x01\n" +
	"\fHeartbeatReq\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"s\n" +
	"\rHeartbeatResp\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12%\n" +
	"\x0esync_timestamp\x18\x02 \x01(\x03R\rsyncTimestamp\x12\x1f\n" +
	"\vnext_action\x18\x03 \x01(\tR\n" +
	"nextAction\"\xc3\x01\n" +
	"\n" +
	"SensingReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\brepo_url\x18\x02 \x01(\tR\arepoUrl\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1b\n" +
	"\ttask_type\x18\x04 \x01(\tR\btaskType\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12 \n" +
	"\vtraceparent\x18\x06 \x01(\tR\vtraceparent\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"\xc6\x01\n" +
	"\vSensingResp\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x121\n" +
	"\ametrics\x18\x04 \x01(\v2\x17.nexus.swarm.v1.MetricsR\ametrics\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12#\n" +
	"\rresults_patch\x18\x06 \x01(\fR\fresultsPatch\"\xcf\x01\n" +
	"\aMetrics\x120\n" +
	"\x14selection_latency_us\x18\x01 \x01(\x03R\x12selectionLatencyUs\x12,\n" +
	"\x12network_latency_ms\x18\x02 \x01(\x03R\x10networkLatencyMs\x12!\n" +
	"\fexecution_ms\x18\x03 \x01(\x03R\vexecutionMs\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12)\n" +
	"\x10confidence_score\x18\x05 \x01(\x02R\x0fconfidenceScore2\xf0\x01\n" +
	"\fSwarmManager\x12J\n" +
	"\tHeartbeat\x12\x1c.nexus.swarm.v1.HeartbeatReq\x1a\x1d.nexus.swarm.v1.HeartbeatResp\"\x00\x12N\n" +
	"\rSensingStream\x12\x1a.nexus.swarm.v1.SensingReq\x1a\x1b.nexus.swarm.v1.SensingResp\"\x00(\x010\x01\x12D\n" +
	"\aSensing\x12\x1a.nexus.swarm.v1.SensingReq\x1a\x1b.nexus.swarm.v1.SensingResp\"\x00B\x17Z\x15nexus-swarm/api/protob\x06proto3"

var (
	file_swarm_proto_rawDescOnce sync.Once
	file_swarm_proto_rawDescData []byte
)

func file_swarm_proto_rawDescGZIP() []byte {
	file_swarm_proto_rawDescOnce.Do(func() {
		file_swarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swarm_proto_rawDesc), len(file_swarm_proto_rawDesc)))
	})
	return file_swarm_proto_rawDescData
}

var file_swarm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_swarm_proto_goTypes = []any{
	(*HeartbeatReq)(nil),  // 0: nexus.swarm.v1.HeartbeatReq
	(*HeartbeatResp)(nil), // 1: nexus.swarm.v1.HeartbeatResp
	(*SensingReq)(nil),    // 2: nexus.swarm.v1.SensingReq
	(*SensingResp)(nil),   // 3: nexus.swarm.v1.SensingResp
	(*Metrics)(nil),       // 4: nexus.swarm.v1.Metrics
}
var file_swarm_proto_depIdxs = []int32{
	4, // 0: nexus.swarm.v1.SensingResp.metrics:type_name -> nexus.swarm.v1.Metrics
	0, // 1: nexus.swarm.v1.SwarmManager.Heartbeat:input_type -> nexus.swarm.v1.HeartbeatReq
	2, // 2: nexus.swarm.v1.SwarmManager.SensingStream:input_type -> nexus.swarm.v1.SensingReq
	2, // 3: nexus.swarm.v1.SwarmManager.Sensing:input_type -> nexus.swarm.v1.SensingReq
	1, // 4: nexus.swarm.v1.SwarmManager.Heartbeat:output_type -> nexus.swarm.v1.HeartbeatResp
	3, // 5: nexus.swarm.v1.SwarmManager.SensingStream:output_type -> nexus.swarm.v1.SensingResp
	3, // 6: nexus.swarm.v1.SwarmManager.Sensing:output_type -> nexus.swarm.v1.SensingResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_swarm_proto_init() }
func file_swarm_proto_init() {
	if File_swarm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swarm_proto_rawDesc), len(file_swarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swarm_proto_goTypes,
		DependencyIndexes: file_swarm_proto_depIdxs,
		MessageInfos:      file_swarm_proto_msgTypes,
	}.Build()
	File_swarm_proto = out.File
	file_swarm_proto_goTypes = nil
	file_swarm_proto_depIdxs = nil
}
