// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: swarm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwarmManager_Heartbeat_FullMethodName     = "/nexus.swarm.v1.SwarmManager/Heartbeat"
	SwarmManager_SensingStream_FullMethodName = "/nexus.swarm.v1.SwarmManager/SensingStream"
	SwarmManager_Sensing_FullMethodName       = "/nexus.swarm.v1.SwarmManager/Sensing"
)

// SwarmManagerClient is the client API for SwarmManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SwarmManager 定義了 Nexus 聯邦的中心調度與心跳監控
type SwarmManagerClient interface {
	// Heartbeat 用於追蹤節點存活與能力上報
	Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*HeartbeatResp, error)
	// SensingStream 提供雙向串流能力的即時感知審計
	SensingStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SensingReq, SensingResp], error)
	// Sensing (Unary) 保留用於單次快速感知請求
	Sensing(ctx context.Context, in *SensingReq, opts ...grpc.CallOption) (*SensingResp, error)
}

type swarmManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewSwarmManagerClient(cc grpc.ClientConnInterface) SwarmManagerClient {
	return &swarmManagerClient{cc}
}

func (c *swarmManagerClient) Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*HeartbeatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResp)
	err := c.cc.Invoke(ctx, SwarmManager_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swarmManagerClient) SensingStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SensingReq, SensingResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SwarmManager_ServiceDesc.Streams[0], SwarmManager_SensingStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SensingReq, SensingResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SwarmManager_SensingStreamClient = grpc.BidiStreamingClient[SensingReq, SensingResp]

func (c *swarmManagerClient) Sensing(ctx context.Context, in *SensingReq, opts ...grpc.CallOption) (*SensingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensingResp)
	err := c.cc.Invoke(ctx, SwarmManager_Sensing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwarmManagerServer is the server API for SwarmManager service.
// All implementations must embed UnimplementedSwarmManagerServer
// for forward compatibility.
//
// SwarmManager 定義了 Nexus 聯邦的中心調度與心跳監控
type SwarmManagerServer interface {
	// Heartbeat 用於追蹤節點存活與能力上報
	Heartbeat(context.Context, *HeartbeatReq) (*HeartbeatResp, error)
	// SensingStream 提供雙向串流能力的即時感知審計
	SensingStream(grpc.BidiStreamingServer[SensingReq, SensingResp]) error
	// Sensing (Unary) 保留用於單次快速感知請求
	Sensing(context.Context, *SensingReq) (*SensingResp, error)
	mustEmbedUnimplementedSwarmManagerServer()
}

// UnimplementedSwarmManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwarmManagerServer struct{}

func (UnimplementedSwarmManagerServer) Heartbeat(context.Context, *HeartbeatReq) (*HeartbeatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedSwarmManagerServer) SensingStream(grpc.BidiStreamingServer[SensingReq, SensingResp]) error {
	return status.Error(codes.Unimplemented, "method SensingStream not implemented")
}
func (UnimplementedSwarmManagerServer) Sensing(context.Context, *SensingReq) (*SensingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Sensing not implemented")
}
func (UnimplementedSwarmManagerServer) mustEmbedUnimplementedSwarmManagerServer() {}
func (UnimplementedSwarmManagerServer) testEmbeddedByValue()                      {}

// UnsafeSwarmManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwarmManagerServer will
// result in compilation errors.
type UnsafeSwarmManagerServer interface {
	mustEmbedUnimplementedSwarmManagerServer()
}

func RegisterSwarmManagerServer(s grpc.ServiceRegistrar, srv SwarmManagerServer) {
	// If the following call panics, it indicates UnimplementedSwarmManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwarmManager_ServiceDesc, srv)
}

func _SwarmManager_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmManagerServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwarmManager_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmManagerServer).Heartbeat(ctx, req.(*HeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwarmManager_SensingStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SwarmManagerServer).SensingStream(&grpc.GenericServerStream[SensingReq, SensingResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SwarmManager_SensingStreamServer = grpc.BidiStreamingServer[SensingReq, SensingResp]

func _SwarmManager_Sensing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmManagerServer).Sensing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwarmManager_Sensing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmManagerServer).Sensing(ctx, req.(*SensingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SwarmManager_ServiceDesc is the grpc.ServiceDesc for SwarmManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwarmManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.swarm.v1.SwarmManager",
	HandlerType: (*SwarmManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _SwarmManager_Heartbeat_Handler,
		},
		{
			MethodName: "Sensing",
			Handler:    _SwarmManager_Sensing_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SensingStream",
			Handler:       _SwarmManager_SensingStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "swarm.proto",
}
