"""M5 Local Assist and qualified Local Worker bridge package."""

from .assist_adapter import LocalAssistService
from .contracts import (
    M5_LOCAL_ASSIST_REQUEST_SCHEMA,
    M5_LOCAL_ASSIST_RESPONSE_SCHEMA,
    M5_LOCAL_CLAIM_CEILING,
    M5_LOCAL_HANDOFF_SCHEMA,
    M5_LOCAL_HOST_INVENTORY_SCHEMA,
    M5_LOCAL_TELEMETRY_SCHEMA,
    M5_LOCAL_WORKER_REQUEST_SCHEMA,
    M5_LOCAL_WORKER_RESPONSE_SCHEMA,
    QUALIFICATION_NOT_QUALIFIED,
    QUALIFICATION_QUALIFIED,
    QUALIFICATION_RUNNABLE,
    ROLE_BOUNDED_CODE_PATCH,
    ROLE_READ_ONLY_ASSIST,
    ROLE_REPO_RANKING,
    ROLE_TYPED_DECISION,
    BoundedEvidencePacket,
    CandidatePathEntry,
    HandoffContractError,
    HandoffPacket,
    LocalAssistMutationAttemptedError,
    LocalAssistRequest,
    LocalAssistResponse,
    LocalBridgeError,
    LocalWorkerDeniedError,
    LocalWorkerRequest,
    LocalWorkerResponse,
    ModelIdentityMismatchError,
    ResourcePressureError,
    SourceExcerpt,
    StaleBaseError,
    TelemetryRecord,
)
from .deterministic_fallback import (
    build_bounded_evidence_packet,
    build_deterministic_fallback_packet,
)
from .handoff_adapter import (
    create_handoff_from_assist,
    create_handoff_from_worker,
)
from .host_inventory import (
    HostMemoryInfo,
    M5HostInventory,
    ModelIdentityVerificationResult,
    ModelInventoryItem,
    RuntimeInventoryItem,
    inspect_m5_host,
    inspect_models,
    inspect_runtimes,
    verify_model_identity,
)
from .runtimes import (
    LlamaCppRuntime,
    LocalInferenceRuntime,
    MlxRuntime,
    MockLocalRuntime,
    RuntimeExecutionResult,
)
from .telemetry import (
    check_host_resource_safety,
    record_execution_telemetry,
)
from .worker_adapter import LocalWorkerService

__all__ = [
    "BoundedEvidencePacket",
    "CandidatePathEntry",
    "HandoffContractError",
    "HandoffPacket",
    "HostMemoryInfo",
    "LlamaCppRuntime",
    "LocalAssistMutationAttemptedError",
    "LocalAssistRequest",
    "LocalAssistResponse",
    "LocalAssistService",
    "LocalBridgeError",
    "LocalInferenceRuntime",
    "LocalWorkerDeniedError",
    "LocalWorkerRequest",
    "LocalWorkerResponse",
    "LocalWorkerService",
    "M5HostInventory",
    "M5_LOCAL_ASSIST_REQUEST_SCHEMA",
    "M5_LOCAL_ASSIST_RESPONSE_SCHEMA",
    "M5_LOCAL_CLAIM_CEILING",
    "M5_LOCAL_HANDOFF_SCHEMA",
    "M5_LOCAL_HOST_INVENTORY_SCHEMA",
    "M5_LOCAL_TELEMETRY_SCHEMA",
    "M5_LOCAL_WORKER_REQUEST_SCHEMA",
    "M5_LOCAL_WORKER_RESPONSE_SCHEMA",
    "MlxRuntime",
    "MockLocalRuntime",
    "ModelIdentityMismatchError",
    "ModelIdentityVerificationResult",
    "ModelInventoryItem",
    "QUALIFICATION_NOT_QUALIFIED",
    "QUALIFICATION_QUALIFIED",
    "QUALIFICATION_RUNNABLE",
    "ROLE_BOUNDED_CODE_PATCH",
    "ROLE_READ_ONLY_ASSIST",
    "ROLE_REPO_RANKING",
    "ROLE_TYPED_DECISION",
    "ResourcePressureError",
    "RuntimeExecutionResult",
    "RuntimeInventoryItem",
    "SourceExcerpt",
    "StaleBaseError",
    "TelemetryRecord",
    "build_bounded_evidence_packet",
    "build_deterministic_fallback_packet",
    "check_host_resource_safety",
    "create_handoff_from_assist",
    "create_handoff_from_worker",
    "inspect_m5_host",
    "inspect_models",
    "inspect_runtimes",
    "record_execution_telemetry",
    "verify_model_identity",
]
