from __future__ import annotations

from pathlib import Path

from nexus.services.codeintel.skeleton_provider import PythonCodeSkeletonProvider, lookup_implementation


def test_lookup_implementation_returns_exact_span_and_signature(tmp_path: Path) -> None:
    package = tmp_path / "pkg"
    package.mkdir()
    (package / "__init__.py").write_text("", encoding="utf-8")
    (package / "core.py").write_text(
        "\n".join(
            [
                "class Worker:",
                "    \"\"\"Does work.\"\"\"",
                "    def run(self, item):",
                "        return helper(item)",
                "",
                "def helper(item):",
                "    return item + 1",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    result = PythonCodeSkeletonProvider(tmp_path).lookup_implementation("pkg.core.Worker.run")

    assert result.found is True
    assert result.reason == ""
    assert len(result.matches) == 1
    match = result.matches[0]
    assert match.file_path == "pkg/core.py"
    assert match.start_line == 3
    assert match.end_line == 4
    assert match.signature == "def run(self, item)"


def test_lookup_implementation_accepts_unqualified_symbol(tmp_path: Path) -> None:
    (tmp_path / "mod.py").write_text("def target(value):\n    return value\n", encoding="utf-8")

    result = lookup_implementation(tmp_path, "target")

    assert result.found is True
    assert result.matches[0].symbol == "mod.target"
    assert result.matches[0].start_line == 1
    assert result.matches[0].end_line == 2


def test_lookup_implementation_can_limit_search_paths(tmp_path: Path) -> None:
    (tmp_path / "wanted.py").write_text("def target(value):\n    return value\n", encoding="utf-8")
    (tmp_path / "ignored.py").write_text("def other(value):\n    return value\n", encoding="utf-8")

    found = lookup_implementation(tmp_path, "target", search_paths=["wanted.py"])
    missing = lookup_implementation(tmp_path, "other", search_paths=["wanted.py"])

    assert found.found is True
    assert found.matches[0].file_path == "wanted.py"
    assert missing.found is False


def test_lookup_implementation_returns_not_found(tmp_path: Path) -> None:
    (tmp_path / "mod.py").write_text("VALUE = 1\n", encoding="utf-8")

    result = lookup_implementation(tmp_path, "missing")

    assert result.found is False
    assert result.reason == "symbol_not_found"
    assert result.matches == []


def test_lookup_implementation_preserves_design_rationale(tmp_path: Path) -> None:
    (tmp_path / "mod.py").write_text(
        "\n".join(
            [
                "# WHY: keep retry math deterministic for benchmark receipts",
                "def target(value):",
                "    \"\"\"Return a stable value.\"\"\"",
                "    return value",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    result = lookup_implementation(tmp_path, "target")

    assert result.found is True
    match = result.matches[0]
    assert match.rationale_context == (
        "Return a stable value.",
        "WHY: keep retry math deterministic for benchmark receipts",
    )
    assert match.ast_status == "PARSED"


def test_lookup_implementation_filters_autogenerated_rationale(tmp_path: Path) -> None:
    migration_dir = tmp_path / "pkg" / "migrations"
    migration_dir.mkdir(parents=True)
    (migration_dir / "0001_initial.py").write_text(
        "# Generated by Django 5.0\n# WHY: migration comment is not design rationale\n"
        "def target(value):\n    \"\"\"Generated migration helper.\"\"\"\n    return value\n",
        encoding="utf-8",
    )

    result = lookup_implementation(tmp_path, "target")

    assert result.found is True
    assert result.matches[0].rationale_context == ()


def test_lookup_implementation_uses_last_known_good_on_syntax_noise(tmp_path: Path) -> None:
    target = tmp_path / "mod.py"
    target.write_text("def target(value):\n    return value\n", encoding="utf-8")
    provider = PythonCodeSkeletonProvider(tmp_path)

    clean = provider.lookup_implementation("target")
    target.write_text("def target(value):\n    return value +\n", encoding="utf-8")
    fallback = provider.lookup_implementation("target")

    assert clean.found is True
    assert fallback.found is True
    assert fallback.matches[0].ast_status == "LAST_KNOWN_GOOD"


def test_lookup_implementation_can_restore_last_known_good_snapshot(tmp_path: Path) -> None:
    target = tmp_path / "mod.py"
    target.write_text("def target(value):\n    return value\n", encoding="utf-8")
    provider = PythonCodeSkeletonProvider(tmp_path)
    assert provider.lookup_implementation("target").found is True
    snapshot = provider.export_symbol_snapshot()

    target.write_text("def target(value):\n    return value +\n", encoding="utf-8")
    restored = PythonCodeSkeletonProvider(tmp_path)
    restored.load_symbol_snapshot(snapshot)
    result = restored.lookup_implementation("target")

    assert result.found is True
    assert result.matches[0].ast_status == "LAST_KNOWN_GOOD"
