from __future__ import annotations
from typing import Any, List, Dict, Optional, Protocol, Set
from pathlib import Path
from .learn_models import LearnClaim

class LearnContextProtocol(Protocol):
    project_root: Path
    knowledge_dir: Path
    claims_path: Path
    sources_path: Path
    benchmark_candidates_path: Path
    benchmark_bank_path: Path
    reports_dir: Path
    phase_writeback_path: Path
    phase_slo_summary_path: Path
    registry_path: Path
    bench_path: Path
    history_path: Path
    slo_path: Path
    writeback_path: Path

    def load_claims(self) -> List[Dict[str, Any]]: ...
    def _resolve_path(self, p: str | Path) -> Path: ...
    def _save_source_snapshot(self, source_url: str, content: str) -> Path: ...
    def _split_to_claims(self, text: str, source_url: str, topic_hint: str = "") -> List[LearnClaim]: ...
    def _append_claims(self, new_claims: List[LearnClaim]) -> int: ...
    def _sync_registry_after_ingest(self, source_url: str, topic: str) -> None: ...
    def _is_text_candidate(self, p: Path) -> bool: ...
    def _path_priority(self, p: Path) -> int: ...
    def _http_get_text(self, url: str) -> str: ...
    def _http_get_json(self, url: str) -> Dict[str, Any]: ...
    def _parse_github_repo(self, repo_str: str) -> tuple[str, str, str]: ...
    def _looks_like_html(self, text: str) -> bool: ...
    def _clean_text(self, text: str) -> str: ...
    def _extract_tokens(self, topic: str) -> Set[str]: ...
    def _normalize_token(self, tok: str) -> str: ...
    def _is_valid_citation(self, c: Dict[str, Any]) -> bool: ...
    def _claim_strength_weight(self, c: Dict[str, Any]) -> float: ...
    def _claim_pack_score(self, c: Dict[str, Any], topic: str, question: str) -> float: ...
    def _find_conflicts(self, claims: List[Dict[str, Any]]) -> List[Dict[str, Any]]: ...
    def _append_benchmark_candidate(self, **kwargs: Any) -> None: ...
    def _persist_learning_closure(self, **kwargs: Any) -> Dict[str, Any]: ...
