#!/usr/bin/env python3
import json
import os
from pathlib import Path
from datetime import datetime

class IncidentRCAAdapter:
    def __init__(self, root: Path):
        self.root = root
        self.incident_dir = root / "docs" / "incidents"
        self.incident_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(self, task_id: str, error_msg: str, context: dict = None):
        """
        Generates a quick RCA report for a given incident.
        """
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        filename = f"RCA_{datetime.now().strftime('%H%M%S')}_{task_id}.md"
        report_path = self.incident_dir / filename
        
        # Analyze error type
        is_quota = "429" in error_msg or "quota" in error_msg.lower()
        is_auth = "401" in error_msg or "token" in error_msg.lower() or "unauthorized" in error_msg.lower()
        
        recovery_hint = "Sir, please check the logs and manually retry."
        if is_quota:
            recovery_hint = "Quota Exceeded. Recommendation: Wait for refill or switch API Key."
        elif is_auth:
            recovery_hint = "Authentication Failed. Recommendation: Refresh OAuth token via `nexus:auth --refresh`."

        content = f"""# Incident RCA Report: {task_id}

- **Time**: {now}
- **Task ID**: {task_id}
- **Error Type**: {"Quota/RateLimit" if is_quota else "Auth/OAuth" if is_auth else "Execution Failure"}
- **RAW Message**: {error_msg}

## 🔍 Diagnosis
The task failed during execution. Initial automated scan suggests a { 'resource' if (is_quota or is_auth) else 'logic' } related issue.

## 🛠️ Recommended Action
**{recovery_hint}**

---
Generated by Nexus v9 Incident Copilot (Active Adapter)
"""
        report_path.write_text(content, encoding="utf-8")
        
        # Also symlink to LATEST_RCA.md
        latest = self.incident_dir / "LATEST_RCA.md"
        if latest.exists():
            latest.unlink()
        try:
            latest.symlink_to(report_path.relative_to(self.incident_dir))
        except:
            latest.write_text(content, encoding="utf-8") # Fallback for non-symlink systems

        return report_path

if __name__ == "__main__":
    adapter = IncidentRCAAdapter(Path(__file__).resolve().parents[2])
    p = adapter.generate_report("test.task", "Error: 429 Too Many Requests")
    print(f"Report generated at: {p}")
