import csv
import sys
import os
from pathlib import Path
from datetime import datetime

def generate_summary(csv_path: str, output_path: str):
    """📊 Nexus Night Shift Summary Generator (L1)"""
    if not os.path.exists(csv_path):
        print(f"❌ Error: {csv_path} not found.")
        return

    results = []
    with open(csv_path, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            results.append(row)

    if not results:
        print("⚠️ No results to summarize.")
        return

    total = len(results)
    successes = sum(1 for r in results if r.get('status') == 'PASS')
    fail_count = total - successes
    
    # 🎯 Trinity Metrics
    avg_velocity = sum(float(r.get('learning_velocity') or 1.0) for r in results) / total
    policy_hits = sum(1 for r in results if r.get('policy_hit', '').strip())

    # Build Markdown
    report = [
        f"# 🌙 Nexus Night Shift Report - {datetime.now().strftime('%Y-%m-%d')}",
        "",
        "## 📈 Key Indicators",
        f"- **Success Rate**: {successes}/{total} ({ (successes/total)*100:.1f}%)",
        f"- **Avg Learning Velocity**: {avg_velocity:.2f}v",
        f"- **Policy Hit Rate**: {policy_hits}/{total} ({ (policy_hits/total)*100:.1f}%)",
        "",
        "## 🛠️ Failures & Traumas",
    ]

    if fail_count > 0:
        report.append("| Task ID | Status | Phase Path |")
        report.append("| :--- | :--- | :--- |")
        for r in results:
            if r.get('status') != 'PASS':
                task_id = r.get('task_id', 'unknown')
                status = r.get('status', 'FAIL')
                path = r.get('phase_path', 'N/A')
                report.append(f"| {task_id} | {status} | {path} |")
    else:
        report.append("✅ All cases passed. No traumas detected.")

    report.append("\n---\n*Generated by Nexus Night Shift Engine v1.0*")

    Path(output_path).write_text("\n".join(report), encoding='utf-8')
    print(f"✅ Summary generated: {output_path}")

if __name__ == "__main__":
    csv_file = sys.argv[1] if len(sys.argv) > 1 else "ci_benchmark_final_v2.csv"
    out_file = sys.argv[2] if len(sys.argv) > 2 else f"docs/reports/night_shift_{datetime.now().strftime('%Y%m%d')}.md"
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(out_file), exist_ok=True)
    generate_summary(csv_file, out_file)
