from typing import Any, Dict, List, Protocol, runtime_checkable

@runtime_checkable
class MemoryStorage(Protocol):
    def store(self, tenant_id: str, artifact_type: str, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def retrieve(self, query: str, **kwargs) -> List[Dict[str, Any]]: ...
    def search(self, query: str, table: str = "default", limit: int = 5) -> List[Dict[str, Any]]: ...

@runtime_checkable
class CacheStore(Protocol):
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any, ttl: int = None): ...
    def delete(self, key: str): ...
    def sadd(self, key: str, *values): ...
    def smembers(self, key: str) -> set: ...
