from typing import Any, Dict, List, Protocol, runtime_checkable

@runtime_checkable
class MemoryStorage(Protocol):
    def store(self, tenant_id: str, artifact_type: str, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def retrieve(self, query: str, **kwargs) -> List[Dict[str, Any]]: ...
    def scoped_access(self, tenant_id: str) -> "MemoryStorage": ...

@runtime_checkable
class SearchProvider(Protocol):
    def search(self, query: str, table_name: str = "policy", limit: int = 5) -> List[Dict[str, Any]]: ...

@runtime_checkable
class CacheStore(Protocol):
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any, ttl: int = None): ...
    def delete(self, key: str): ...
    def sadd(self, key: str, *values): ...
    def smembers(self, key: str) -> set: ...

@runtime_checkable
class BeliefStore(Protocol):
    def list_beliefs(self, status: str = "ACTIVE") -> List[Dict[str, Any]]: ...

@runtime_checkable
class ConfigStore(Protocol):
    def get_router_bias(self) -> List[float] | None: ...

@runtime_checkable
class JsonlStore(Protocol):
    def read_rows(self, path: str) -> List[Dict[str, Any]]: ...
    def append_row(self, path: str, row: Dict[str, Any]) -> None: ...
    def write_rows(self, path: str, rows: List[Dict[str, Any]]) -> None: ...
