# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import swarm_pb2 as swarm__pb2


class SwarmManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/nexus.swarm.v1.SwarmManager/RegisterNode',
                request_serializer=swarm__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=swarm__pb2.RegisterNodeResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/nexus.swarm.v1.SwarmManager/Heartbeat',
                request_serializer=swarm__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=swarm__pb2.HeartbeatResponse.FromString,
                )
        self.DispatchTask = channel.unary_unary(
                '/nexus.swarm.v1.SwarmManager/DispatchTask',
                request_serializer=swarm__pb2.DispatchTaskRequest.SerializeToString,
                response_deserializer=swarm__pb2.DispatchTaskResponse.FromString,
                )
        self.ReportTask = channel.unary_unary(
                '/nexus.swarm.v1.SwarmManager/ReportTask',
                request_serializer=swarm__pb2.ReportTaskRequest.SerializeToString,
                response_deserializer=swarm__pb2.ReportTaskResponse.FromString,
                )
        self.GetClusterStatus = channel.unary_unary(
                '/nexus.swarm.v1.SwarmManager/GetClusterStatus',
                request_serializer=swarm__pb2.GetClusterStatusRequest.SerializeToString,
                response_deserializer=swarm__pb2.GetClusterStatusResponse.FromString,
                )


class SwarmManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterNode(self, request, context):
        """控制面 指令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DispatchTask(self, request, context):
        """任務面 指令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterStatus(self, request, context):
        """狀態面 指令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SwarmManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=swarm__pb2.RegisterNodeRequest.FromString,
                    response_serializer=swarm__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=swarm__pb2.HeartbeatRequest.FromString,
                    response_serializer=swarm__pb2.HeartbeatResponse.SerializeToString,
            ),
            'DispatchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchTask,
                    request_deserializer=swarm__pb2.DispatchTaskRequest.FromString,
                    response_serializer=swarm__pb2.DispatchTaskResponse.SerializeToString,
            ),
            'ReportTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTask,
                    request_deserializer=swarm__pb2.ReportTaskRequest.FromString,
                    response_serializer=swarm__pb2.ReportTaskResponse.SerializeToString,
            ),
            'GetClusterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterStatus,
                    request_deserializer=swarm__pb2.GetClusterStatusRequest.FromString,
                    response_serializer=swarm__pb2.GetClusterStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.swarm.v1.SwarmManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SwarmManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nexus.swarm.v1.SwarmManager/RegisterNode',
            swarm__pb2.RegisterNodeRequest.SerializeToString,
            swarm__pb2.RegisterNodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nexus.swarm.v1.SwarmManager/Heartbeat',
            swarm__pb2.HeartbeatRequest.SerializeToString,
            swarm__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DispatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nexus.swarm.v1.SwarmManager/DispatchTask',
            swarm__pb2.DispatchTaskRequest.SerializeToString,
            swarm__pb2.DispatchTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nexus.swarm.v1.SwarmManager/ReportTask',
            swarm__pb2.ReportTaskRequest.SerializeToString,
            swarm__pb2.ReportTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClusterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nexus.swarm.v1.SwarmManager/GetClusterStatus',
            swarm__pb2.GetClusterStatusRequest.SerializeToString,
            swarm__pb2.GetClusterStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
