"""
CI Report Generator — 讀取 benchmark JSONL，產生 Markdown 報告
寫入 GITHUB_STEP_SUMMARY 並（可選）更新 README.md 中的 Badge
"""

import argparse
import json
import os
import re
from datetime import datetime
from pathlib import Path

NEXUS_ROOT = Path(__file__).parent.parent.parent
README_PATH = NEXUS_ROOT / "README.md"


def load_results(jsonl_path: str) -> list[dict]:
    results = []
    with open(jsonl_path, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                results.append(json.loads(line))
    return results


def generate_markdown(results: list[dict], run_date: str) -> str:
    total = len(results)
    passed = sum(1 for r in results if r.get("pass@1"))
    rate = passed / total * 100 if total > 0 else 0

    timeout_count = sum(1 for r in results if r.get("status") == "timeout")
    error_count = sum(1 for r in results if r.get("status") == "error")

    badge_color = "brightgreen" if rate >= 80 else "yellow" if rate >= 60 else "red"
    badge_url = f"https://img.shields.io/badge/pass%401-{rate:.0f}%25-{badge_color}"

    lines = [
        f"## 📊 Nexus Benchmark Report — {run_date}",
        "",
        f"![pass@1]({badge_url})",
        "",
        "### Summary",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| **Pass@1** | **{rate:.1f}%** ({passed}/{total}) |",
        f"| Timeout | {timeout_count} |",
        f"| Error | {error_count} |",
        f"| Cases Ran | {total} |",
        "",
        "### Per-Case Results",
        "",
        "| Task ID | Status | Elapsed |",
        "|---|---|---|",
    ]

    for r in results:
        icon = "✅" if r.get("pass@1") else "❌"
        status = r.get("status", "unknown")
        elapsed = r.get("elapsed_seconds", 0)
        lines.append(f"| `{r['task_id']}` | {icon} {status} | {elapsed:.1f}s |")

    lines += [
        "",
        "---",
        f"> Generated by Nexus Benchmark CI — {datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')}",
    ]

    return "\n".join(lines)


def update_readme_badge(rate: float):
    """使用 Regex 更新 README.md 中的 pass@1 badge"""
    if not README_PATH.exists():
        print("⚠️  README.md not found, skipping badge update.")
        return

    content = README_PATH.read_text(encoding="utf-8")
    badge_color = "brightgreen" if rate >= 80 else "yellow" if rate >= 60 else "red"
    new_badge = f"https://img.shields.io/badge/pass%401-{rate:.0f}%25-{badge_color}"

    # 替換既有 pass@1 badge（如果存在）
    updated, count = re.subn(
        r"https://img\.shields\.io/badge/pass%401-[\d.]+%25-\w+",
        new_badge,
        content,
    )

    if count > 0:
        README_PATH.write_text(updated, encoding="utf-8")
        print(f"✅ README.md badge updated → {rate:.1f}%")
    else:
        print("ℹ️  No existing pass@1 badge in README.md, skipping update.")


def main():
    parser = argparse.ArgumentParser(description="Nexus CI Report Generator")
    parser.add_argument("--input", type=str, required=True, help="Path to JSONL results")
    parser.add_argument("--summary-output", type=str, default="benchmark_summary.md")
    parser.add_argument("--update-readme", action="store_true", help="Update README.md badge")
    args = parser.parse_args()

    run_date = datetime.utcnow().strftime("%Y-%m-%d")
    results = load_results(args.input)

    md = generate_markdown(results, run_date)

    # Write to file
    Path(args.summary_output).write_text(md, encoding="utf-8")
    print(f"📝 Markdown report written to: {args.summary_output}")

    # Write to GITHUB_STEP_SUMMARY (if in CI)
    gss = os.environ.get("GITHUB_STEP_SUMMARY")
    if gss:
        with open(gss, "a", encoding="utf-8") as f:
            f.write(md + "\n")
        print("✅ GITHUB_STEP_SUMMARY updated")

    # Optionally update README badge
    if args.update_readme or os.environ.get("CI"):
        total = len(results)
        passed = sum(1 for r in results if r.get("pass@1"))
        rate = passed / total * 100 if total > 0 else 0
        update_readme_badge(rate)


if __name__ == "__main__":
    main()
