// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: federation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Federation_DiscoverPeers_FullMethodName        = "/nexus.swarm.federation.v1.Federation/DiscoverPeers"
	Federation_HeartbeatFederation_FullMethodName  = "/nexus.swarm.federation.v1.Federation/HeartbeatFederation"
	Federation_RouteTask_FullMethodName            = "/nexus.swarm.federation.v1.Federation/RouteTask"
	Federation_GlobalLeaderElection_FullMethodName = "/nexus.swarm.federation.v1.Federation/GlobalLeaderElection"
)

// FederationClient is the client API for Federation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FederationClient interface {
	// 🛡️ Discovery & Identity
	DiscoverPeers(ctx context.Context, in *DiscoverPeersRequest, opts ...grpc.CallOption) (*DiscoverPeersResponse, error)
	HeartbeatFederation(ctx context.Context, in *HeartbeatFederationRequest, opts ...grpc.CallOption) (*HeartbeatFederationResponse, error)
	// 🛡️ Operations
	RouteTask(ctx context.Context, in *RouteTaskRequest, opts ...grpc.CallOption) (*RouteTaskResponse, error)
	// 🛡️ Consensus
	GlobalLeaderElection(ctx context.Context, in *GlobalLeaderElectionRequest, opts ...grpc.CallOption) (*GlobalLeaderElectionResponse, error)
}

type federationClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationClient(cc grpc.ClientConnInterface) FederationClient {
	return &federationClient{cc}
}

func (c *federationClient) DiscoverPeers(ctx context.Context, in *DiscoverPeersRequest, opts ...grpc.CallOption) (*DiscoverPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverPeersResponse)
	err := c.cc.Invoke(ctx, Federation_DiscoverPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationClient) HeartbeatFederation(ctx context.Context, in *HeartbeatFederationRequest, opts ...grpc.CallOption) (*HeartbeatFederationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatFederationResponse)
	err := c.cc.Invoke(ctx, Federation_HeartbeatFederation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationClient) RouteTask(ctx context.Context, in *RouteTaskRequest, opts ...grpc.CallOption) (*RouteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteTaskResponse)
	err := c.cc.Invoke(ctx, Federation_RouteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationClient) GlobalLeaderElection(ctx context.Context, in *GlobalLeaderElectionRequest, opts ...grpc.CallOption) (*GlobalLeaderElectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GlobalLeaderElectionResponse)
	err := c.cc.Invoke(ctx, Federation_GlobalLeaderElection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederationServer is the server API for Federation service.
// All implementations must embed UnimplementedFederationServer
// for forward compatibility.
type FederationServer interface {
	// 🛡️ Discovery & Identity
	DiscoverPeers(context.Context, *DiscoverPeersRequest) (*DiscoverPeersResponse, error)
	HeartbeatFederation(context.Context, *HeartbeatFederationRequest) (*HeartbeatFederationResponse, error)
	// 🛡️ Operations
	RouteTask(context.Context, *RouteTaskRequest) (*RouteTaskResponse, error)
	// 🛡️ Consensus
	GlobalLeaderElection(context.Context, *GlobalLeaderElectionRequest) (*GlobalLeaderElectionResponse, error)
	mustEmbedUnimplementedFederationServer()
}

// UnimplementedFederationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederationServer struct{}

func (UnimplementedFederationServer) DiscoverPeers(context.Context, *DiscoverPeersRequest) (*DiscoverPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverPeers not implemented")
}
func (UnimplementedFederationServer) HeartbeatFederation(context.Context, *HeartbeatFederationRequest) (*HeartbeatFederationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HeartbeatFederation not implemented")
}
func (UnimplementedFederationServer) RouteTask(context.Context, *RouteTaskRequest) (*RouteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteTask not implemented")
}
func (UnimplementedFederationServer) GlobalLeaderElection(context.Context, *GlobalLeaderElectionRequest) (*GlobalLeaderElectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GlobalLeaderElection not implemented")
}
func (UnimplementedFederationServer) mustEmbedUnimplementedFederationServer() {}
func (UnimplementedFederationServer) testEmbeddedByValue()                    {}

// UnsafeFederationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationServer will
// result in compilation errors.
type UnsafeFederationServer interface {
	mustEmbedUnimplementedFederationServer()
}

func RegisterFederationServer(s grpc.ServiceRegistrar, srv FederationServer) {
	// If the following call panics, it indicates UnimplementedFederationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Federation_ServiceDesc, srv)
}

func _Federation_DiscoverPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).DiscoverPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_DiscoverPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).DiscoverPeers(ctx, req.(*DiscoverPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Federation_HeartbeatFederation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatFederationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).HeartbeatFederation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_HeartbeatFederation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).HeartbeatFederation(ctx, req.(*HeartbeatFederationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Federation_RouteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).RouteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_RouteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).RouteTask(ctx, req.(*RouteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Federation_GlobalLeaderElection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalLeaderElectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServer).GlobalLeaderElection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Federation_GlobalLeaderElection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServer).GlobalLeaderElection(ctx, req.(*GlobalLeaderElectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Federation_ServiceDesc is the grpc.ServiceDesc for Federation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Federation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.swarm.federation.v1.Federation",
	HandlerType: (*FederationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DiscoverPeers",
			Handler:    _Federation_DiscoverPeers_Handler,
		},
		{
			MethodName: "HeartbeatFederation",
			Handler:    _Federation_HeartbeatFederation_Handler,
		},
		{
			MethodName: "RouteTask",
			Handler:    _Federation_RouteTask_Handler,
		},
		{
			MethodName: "GlobalLeaderElection",
			Handler:    _Federation_GlobalLeaderElection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "federation.proto",
}
