# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import swarm_pb2 as swarm__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swarm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SwarmManagerStub(object):
    """SwarmManager 定義了 Nexus 聯邦的中心調度與心跳監控
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/nexus.swarm.v1.SwarmManager/Heartbeat',
                request_serializer=swarm__pb2.HeartbeatReq.SerializeToString,
                response_deserializer=swarm__pb2.HeartbeatResp.FromString,
                _registered_method=True)
        self.SensingStream = channel.stream_stream(
                '/nexus.swarm.v1.SwarmManager/SensingStream',
                request_serializer=swarm__pb2.SensingReq.SerializeToString,
                response_deserializer=swarm__pb2.SensingResp.FromString,
                _registered_method=True)
        self.Sensing = channel.unary_unary(
                '/nexus.swarm.v1.SwarmManager/Sensing',
                request_serializer=swarm__pb2.SensingReq.SerializeToString,
                response_deserializer=swarm__pb2.SensingResp.FromString,
                _registered_method=True)


class SwarmManagerServicer(object):
    """SwarmManager 定義了 Nexus 聯邦的中心調度與心跳監控
    """

    def Heartbeat(self, request, context):
        """Heartbeat 用於追蹤節點存活與能力上報
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SensingStream(self, request_iterator, context):
        """SensingStream 提供雙向串流能力的即時感知審計
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sensing(self, request, context):
        """Sensing (Unary) 保留用於單次快速感知請求
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SwarmManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=swarm__pb2.HeartbeatReq.FromString,
                    response_serializer=swarm__pb2.HeartbeatResp.SerializeToString,
            ),
            'SensingStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SensingStream,
                    request_deserializer=swarm__pb2.SensingReq.FromString,
                    response_serializer=swarm__pb2.SensingResp.SerializeToString,
            ),
            'Sensing': grpc.unary_unary_rpc_method_handler(
                    servicer.Sensing,
                    request_deserializer=swarm__pb2.SensingReq.FromString,
                    response_serializer=swarm__pb2.SensingResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.swarm.v1.SwarmManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.swarm.v1.SwarmManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SwarmManager(object):
    """SwarmManager 定義了 Nexus 聯邦的中心調度與心跳監控
    """

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.swarm.v1.SwarmManager/Heartbeat',
            swarm__pb2.HeartbeatReq.SerializeToString,
            swarm__pb2.HeartbeatResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SensingStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nexus.swarm.v1.SwarmManager/SensingStream',
            swarm__pb2.SensingReq.SerializeToString,
            swarm__pb2.SensingResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sensing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.swarm.v1.SwarmManager/Sensing',
            swarm__pb2.SensingReq.SerializeToString,
            swarm__pb2.SensingResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
