# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swarm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swarm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bswarm.proto\x12\x0enexus.swarm.v1\"X\n\x0cHeartbeatReq\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x02 \x03(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"N\n\rHeartbeatResp\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x16\n\x0esync_timestamp\x18\x02 \x01(\x03\x12\x13\n\x0bnext_action\x18\x03 \x01(\t\"\x85\x01\n\nSensingReq\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08repo_url\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x11\n\ttask_type\x18\x04 \x01(\t\x12\r\n\x05token\x18\x05 \x01(\t\x12\x13\n\x0btraceparent\x18\x06 \x01(\t\x12\x0f\n\x07payload\x18\x07 \x01(\x0c\"\x8f\x01\n\x0bSensingResp\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12(\n\x07metrics\x18\x04 \x01(\x0b\x32\x17.nexus.swarm.v1.Metrics\x12\r\n\x05\x65rror\x18\x05 \x01(\t\x12\x15\n\rresults_patch\x18\x06 \x01(\x0c\"\x83\x01\n\x07Metrics\x12\x1c\n\x14selection_latency_us\x18\x01 \x01(\x03\x12\x1a\n\x12network_latency_ms\x18\x02 \x01(\x03\x12\x14\n\x0c\x65xecution_ms\x18\x03 \x01(\x03\x12\x0e\n\x06region\x18\x04 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x05 \x01(\x02\x32\xf0\x01\n\x0cSwarmManager\x12J\n\tHeartbeat\x12\x1c.nexus.swarm.v1.HeartbeatReq\x1a\x1d.nexus.swarm.v1.HeartbeatResp\"\x00\x12N\n\rSensingStream\x12\x1a.nexus.swarm.v1.SensingReq\x1a\x1b.nexus.swarm.v1.SensingResp\"\x00(\x01\x30\x01\x12\x44\n\x07Sensing\x12\x1a.nexus.swarm.v1.SensingReq\x1a\x1b.nexus.swarm.v1.SensingResp\"\x00\x42\x17Z\x15nexus-swarm/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swarm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025nexus-swarm/api/proto'
  _globals['_HEARTBEATREQ']._serialized_start=31
  _globals['_HEARTBEATREQ']._serialized_end=119
  _globals['_HEARTBEATRESP']._serialized_start=121
  _globals['_HEARTBEATRESP']._serialized_end=199
  _globals['_SENSINGREQ']._serialized_start=202
  _globals['_SENSINGREQ']._serialized_end=335
  _globals['_SENSINGRESP']._serialized_start=338
  _globals['_SENSINGRESP']._serialized_end=481
  _globals['_METRICS']._serialized_start=484
  _globals['_METRICS']._serialized_end=615
  _globals['_SWARMMANAGER']._serialized_start=618
  _globals['_SWARMMANAGER']._serialized_end=858
# @@protoc_insertion_point(module_scope)
