// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: nexus.proto

package nexus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NexusCore_LeaseWorktree_FullMethodName   = "/nexus.v1.NexusCore/LeaseWorktree"
	NexusCore_HarvestWorktree_FullMethodName = "/nexus.v1.NexusCore/HarvestWorktree"
	NexusCore_CancelLease_FullMethodName     = "/nexus.v1.NexusCore/CancelLease"
	NexusCore_EvaluatePolicy_FullMethodName  = "/nexus.v1.NexusCore/EvaluatePolicy"
	NexusCore_HealthCheck_FullMethodName     = "/nexus.v1.NexusCore/HealthCheck"
)

// NexusCoreClient is the client API for NexusCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 📦 Core System Services (Rust Skeleton)
type NexusCoreClient interface {
	// Worktree Management
	LeaseWorktree(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*WorktreeLease, error)
	HarvestWorktree(ctx context.Context, in *HarvestRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	CancelLease(ctx context.Context, in *CancelLeaseRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	// Governance & Policy
	EvaluatePolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyDecision, error)
	// Health & Monitoring
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type nexusCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewNexusCoreClient(cc grpc.ClientConnInterface) NexusCoreClient {
	return &nexusCoreClient{cc}
}

func (c *nexusCoreClient) LeaseWorktree(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (*WorktreeLease, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorktreeLease)
	err := c.cc.Invoke(ctx, NexusCore_LeaseWorktree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusCoreClient) HarvestWorktree(ctx context.Context, in *HarvestRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, NexusCore_HarvestWorktree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusCoreClient) CancelLease(ctx context.Context, in *CancelLeaseRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, NexusCore_CancelLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusCoreClient) EvaluatePolicy(ctx context.Context, in *PolicyRequest, opts ...grpc.CallOption) (*PolicyDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyDecision)
	err := c.cc.Invoke(ctx, NexusCore_EvaluatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusCoreClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NexusCore_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NexusCoreServer is the server API for NexusCore service.
// All implementations must embed UnimplementedNexusCoreServer
// for forward compatibility.
//
// 📦 Core System Services (Rust Skeleton)
type NexusCoreServer interface {
	// Worktree Management
	LeaseWorktree(context.Context, *LeaseRequest) (*WorktreeLease, error)
	HarvestWorktree(context.Context, *HarvestRequest) (*ActionResponse, error)
	CancelLease(context.Context, *CancelLeaseRequest) (*ActionResponse, error)
	// Governance & Policy
	EvaluatePolicy(context.Context, *PolicyRequest) (*PolicyDecision, error)
	// Health & Monitoring
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedNexusCoreServer()
}

// UnimplementedNexusCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNexusCoreServer struct{}

func (UnimplementedNexusCoreServer) LeaseWorktree(context.Context, *LeaseRequest) (*WorktreeLease, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaseWorktree not implemented")
}
func (UnimplementedNexusCoreServer) HarvestWorktree(context.Context, *HarvestRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HarvestWorktree not implemented")
}
func (UnimplementedNexusCoreServer) CancelLease(context.Context, *CancelLeaseRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelLease not implemented")
}
func (UnimplementedNexusCoreServer) EvaluatePolicy(context.Context, *PolicyRequest) (*PolicyDecision, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluatePolicy not implemented")
}
func (UnimplementedNexusCoreServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNexusCoreServer) mustEmbedUnimplementedNexusCoreServer() {}
func (UnimplementedNexusCoreServer) testEmbeddedByValue()                   {}

// UnsafeNexusCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NexusCoreServer will
// result in compilation errors.
type UnsafeNexusCoreServer interface {
	mustEmbedUnimplementedNexusCoreServer()
}

func RegisterNexusCoreServer(s grpc.ServiceRegistrar, srv NexusCoreServer) {
	// If the following call panics, it indicates UnimplementedNexusCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NexusCore_ServiceDesc, srv)
}

func _NexusCore_LeaseWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusCoreServer).LeaseWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusCore_LeaseWorktree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusCoreServer).LeaseWorktree(ctx, req.(*LeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusCore_HarvestWorktree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HarvestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusCoreServer).HarvestWorktree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusCore_HarvestWorktree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusCoreServer).HarvestWorktree(ctx, req.(*HarvestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusCore_CancelLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusCoreServer).CancelLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusCore_CancelLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusCoreServer).CancelLease(ctx, req.(*CancelLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusCore_EvaluatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusCoreServer).EvaluatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusCore_EvaluatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusCoreServer).EvaluatePolicy(ctx, req.(*PolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusCore_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusCoreServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusCore_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusCoreServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NexusCore_ServiceDesc is the grpc.ServiceDesc for NexusCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NexusCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.v1.NexusCore",
	HandlerType: (*NexusCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LeaseWorktree",
			Handler:    _NexusCore_LeaseWorktree_Handler,
		},
		{
			MethodName: "HarvestWorktree",
			Handler:    _NexusCore_HarvestWorktree_Handler,
		},
		{
			MethodName: "CancelLease",
			Handler:    _NexusCore_CancelLease_Handler,
		},
		{
			MethodName: "EvaluatePolicy",
			Handler:    _NexusCore_EvaluatePolicy_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NexusCore_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexus.proto",
}

const (
	NexusSwarm_RunPhase_FullMethodName    = "/nexus.v1.NexusSwarm/RunPhase"
	NexusSwarm_EmitMetrics_FullMethodName = "/nexus.v1.NexusSwarm/EmitMetrics"
)

// NexusSwarmClient is the client API for NexusSwarm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 🛰️ Swarm & Orchestration Services (Go Bus)
type NexusSwarmClient interface {
	// Phase Orchestration
	RunPhase(ctx context.Context, in *PhaseRequest, opts ...grpc.CallOption) (*PhaseOutcome, error)
	// Telemetry & Metrics
	EmitMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricEvent, ActionResponse], error)
}

type nexusSwarmClient struct {
	cc grpc.ClientConnInterface
}

func NewNexusSwarmClient(cc grpc.ClientConnInterface) NexusSwarmClient {
	return &nexusSwarmClient{cc}
}

func (c *nexusSwarmClient) RunPhase(ctx context.Context, in *PhaseRequest, opts ...grpc.CallOption) (*PhaseOutcome, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PhaseOutcome)
	err := c.cc.Invoke(ctx, NexusSwarm_RunPhase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nexusSwarmClient) EmitMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricEvent, ActionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NexusSwarm_ServiceDesc.Streams[0], NexusSwarm_EmitMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricEvent, ActionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NexusSwarm_EmitMetricsClient = grpc.ClientStreamingClient[MetricEvent, ActionResponse]

// NexusSwarmServer is the server API for NexusSwarm service.
// All implementations must embed UnimplementedNexusSwarmServer
// for forward compatibility.
//
// 🛰️ Swarm & Orchestration Services (Go Bus)
type NexusSwarmServer interface {
	// Phase Orchestration
	RunPhase(context.Context, *PhaseRequest) (*PhaseOutcome, error)
	// Telemetry & Metrics
	EmitMetrics(grpc.ClientStreamingServer[MetricEvent, ActionResponse]) error
	mustEmbedUnimplementedNexusSwarmServer()
}

// UnimplementedNexusSwarmServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNexusSwarmServer struct{}

func (UnimplementedNexusSwarmServer) RunPhase(context.Context, *PhaseRequest) (*PhaseOutcome, error) {
	return nil, status.Error(codes.Unimplemented, "method RunPhase not implemented")
}
func (UnimplementedNexusSwarmServer) EmitMetrics(grpc.ClientStreamingServer[MetricEvent, ActionResponse]) error {
	return status.Error(codes.Unimplemented, "method EmitMetrics not implemented")
}
func (UnimplementedNexusSwarmServer) mustEmbedUnimplementedNexusSwarmServer() {}
func (UnimplementedNexusSwarmServer) testEmbeddedByValue()                    {}

// UnsafeNexusSwarmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NexusSwarmServer will
// result in compilation errors.
type UnsafeNexusSwarmServer interface {
	mustEmbedUnimplementedNexusSwarmServer()
}

func RegisterNexusSwarmServer(s grpc.ServiceRegistrar, srv NexusSwarmServer) {
	// If the following call panics, it indicates UnimplementedNexusSwarmServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NexusSwarm_ServiceDesc, srv)
}

func _NexusSwarm_RunPhase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusSwarmServer).RunPhase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusSwarm_RunPhase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusSwarmServer).RunPhase(ctx, req.(*PhaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NexusSwarm_EmitMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NexusSwarmServer).EmitMetrics(&grpc.GenericServerStream[MetricEvent, ActionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NexusSwarm_EmitMetricsServer = grpc.ClientStreamingServer[MetricEvent, ActionResponse]

// NexusSwarm_ServiceDesc is the grpc.ServiceDesc for NexusSwarm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NexusSwarm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.v1.NexusSwarm",
	HandlerType: (*NexusSwarmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunPhase",
			Handler:    _NexusSwarm_RunPhase_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EmitMetrics",
			Handler:       _NexusSwarm_EmitMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "nexus.proto",
}
