// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: nexus.proto

package nexus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 🌀 Nexus Phase Lifecycle (PXDRAC Standard)
type PhaseID int32

const (
	PhaseID_PHASE_UNKNOWN     PhaseID = 0
	PhaseID_PHASE_PLAN        PhaseID = 1
	PhaseID_PHASE_RESEARCH    PhaseID = 2 // ✅ Synced with 'X' Research Phase
	PhaseID_PHASE_DIAGNOSE    PhaseID = 3
	PhaseID_PHASE_REPAIR      PhaseID = 4
	PhaseID_PHASE_AUDIT       PhaseID = 5
	PhaseID_PHASE_CRYSTALLIZE PhaseID = 6
)

// Enum value maps for PhaseID.
var (
	PhaseID_name = map[int32]string{
		0: "PHASE_UNKNOWN",
		1: "PHASE_PLAN",
		2: "PHASE_RESEARCH",
		3: "PHASE_DIAGNOSE",
		4: "PHASE_REPAIR",
		5: "PHASE_AUDIT",
		6: "PHASE_CRYSTALLIZE",
	}
	PhaseID_value = map[string]int32{
		"PHASE_UNKNOWN":     0,
		"PHASE_PLAN":        1,
		"PHASE_RESEARCH":    2,
		"PHASE_DIAGNOSE":    3,
		"PHASE_REPAIR":      4,
		"PHASE_AUDIT":       5,
		"PHASE_CRYSTALLIZE": 6,
	}
)

func (x PhaseID) Enum() *PhaseID {
	p := new(PhaseID)
	*p = x
	return p
}

func (x PhaseID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhaseID) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_proto_enumTypes[0].Descriptor()
}

func (PhaseID) Type() protoreflect.EnumType {
	return &file_nexus_proto_enumTypes[0]
}

func (x PhaseID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhaseID.Descriptor instead.
func (PhaseID) EnumDescriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{0}
}

type PolicyDecision_SentinelIntents int32

const (
	PolicyDecision_SAFE_READ       PolicyDecision_SentinelIntents = 0
	PolicyDecision_DANGEROUS_WRITE PolicyDecision_SentinelIntents = 1
	PolicyDecision_HUMAN_REVIEW    PolicyDecision_SentinelIntents = 2
	PolicyDecision_OOS_ACCESS      PolicyDecision_SentinelIntents = 3
)

// Enum value maps for PolicyDecision_SentinelIntents.
var (
	PolicyDecision_SentinelIntents_name = map[int32]string{
		0: "SAFE_READ",
		1: "DANGEROUS_WRITE",
		2: "HUMAN_REVIEW",
		3: "OOS_ACCESS",
	}
	PolicyDecision_SentinelIntents_value = map[string]int32{
		"SAFE_READ":       0,
		"DANGEROUS_WRITE": 1,
		"HUMAN_REVIEW":    2,
		"OOS_ACCESS":      3,
	}
)

func (x PolicyDecision_SentinelIntents) Enum() *PolicyDecision_SentinelIntents {
	p := new(PolicyDecision_SentinelIntents)
	*p = x
	return p
}

func (x PolicyDecision_SentinelIntents) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyDecision_SentinelIntents) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_proto_enumTypes[1].Descriptor()
}

func (PolicyDecision_SentinelIntents) Type() protoreflect.EnumType {
	return &file_nexus_proto_enumTypes[1]
}

func (x PolicyDecision_SentinelIntents) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyDecision_SentinelIntents.Descriptor instead.
func (PolicyDecision_SentinelIntents) EnumDescriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{5, 0}
}

type PhaseOutcome_Status int32

const (
	PhaseOutcome_SUCCESS      PhaseOutcome_Status = 0
	PhaseOutcome_FAILED       PhaseOutcome_Status = 1
	PhaseOutcome_HUMAN_REVIEW PhaseOutcome_Status = 2
	PhaseOutcome_ESCALATED    PhaseOutcome_Status = 3
)

// Enum value maps for PhaseOutcome_Status.
var (
	PhaseOutcome_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
		2: "HUMAN_REVIEW",
		3: "ESCALATED",
	}
	PhaseOutcome_Status_value = map[string]int32{
		"SUCCESS":      0,
		"FAILED":       1,
		"HUMAN_REVIEW": 2,
		"ESCALATED":    3,
	}
)

func (x PhaseOutcome_Status) Enum() *PhaseOutcome_Status {
	p := new(PhaseOutcome_Status)
	*p = x
	return p
}

func (x PhaseOutcome_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhaseOutcome_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_proto_enumTypes[2].Descriptor()
}

func (PhaseOutcome_Status) Type() protoreflect.EnumType {
	return &file_nexus_proto_enumTypes[2]
}

func (x PhaseOutcome_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhaseOutcome_Status.Descriptor instead.
func (PhaseOutcome_Status) EnumDescriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{7, 0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_proto_enumTypes[3].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_nexus_proto_enumTypes[3]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{11, 0}
}

type LeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BranchHint    string                 `protobuf:"bytes,2,opt,name=branch_hint,json=branchHint,proto3" json:"branch_hint,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_nexus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{0}
}

func (x *LeaseRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *LeaseRequest) GetBranchHint() string {
	if x != nil {
		return x.BranchHint
	}
	return ""
}

func (x *LeaseRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type WorktreeLease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	BranchName    string                 `protobuf:"bytes,3,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorktreeLease) Reset() {
	*x = WorktreeLease{}
	mi := &file_nexus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorktreeLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorktreeLease) ProtoMessage() {}

func (x *WorktreeLease) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorktreeLease.ProtoReflect.Descriptor instead.
func (*WorktreeLease) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{1}
}

func (x *WorktreeLease) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *WorktreeLease) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorktreeLease) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *WorktreeLease) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type HarvestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ForceMerge    bool                   `protobuf:"varint,2,opt,name=force_merge,json=forceMerge,proto3" json:"force_merge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarvestRequest) Reset() {
	*x = HarvestRequest{}
	mi := &file_nexus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarvestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestRequest) ProtoMessage() {}

func (x *HarvestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestRequest.ProtoReflect.Descriptor instead.
func (*HarvestRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{2}
}

func (x *HarvestRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *HarvestRequest) GetForceMerge() bool {
	if x != nil {
		return x.ForceMerge
	}
	return false
}

type CancelLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelLeaseRequest) Reset() {
	*x = CancelLeaseRequest{}
	mi := &file_nexus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLeaseRequest) ProtoMessage() {}

func (x *CancelLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLeaseRequest.ProtoReflect.Descriptor instead.
func (*CancelLeaseRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{3}
}

func (x *CancelLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *CancelLeaseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Context       string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	IntentPrompt  string                 `protobuf:"bytes,5,opt,name=intent_prompt,json=intentPrompt,proto3" json:"intent_prompt,omitempty"` // ✅ v2.2 Neural Sentinel: LLM Gating Prompt
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRequest) Reset() {
	*x = PolicyRequest{}
	mi := &file_nexus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRequest) ProtoMessage() {}

func (x *PolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRequest.ProtoReflect.Descriptor instead.
func (*PolicyRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{4}
}

func (x *PolicyRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PolicyRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PolicyRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PolicyRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *PolicyRequest) GetIntentPrompt() string {
	if x != nil {
		return x.IntentPrompt
	}
	return ""
}

type PolicyDecision struct {
	state              protoimpl.MessageState         `protogen:"open.v1"`
	DecisionId         string                         `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Allow              bool                           `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	Reason             string                         `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Intent             PolicyDecision_SentinelIntents `protobuf:"varint,4,opt,name=intent,proto3,enum=nexus.v1.PolicyDecision_SentinelIntents" json:"intent,omitempty"` // ✅ v2.2 Neural: LLM Categorization
	EnforcementActions []string                       `protobuf:"bytes,5,rep,name=enforcement_actions,json=enforcementActions,proto3" json:"enforcement_actions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PolicyDecision) Reset() {
	*x = PolicyDecision{}
	mi := &file_nexus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDecision) ProtoMessage() {}

func (x *PolicyDecision) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDecision.ProtoReflect.Descriptor instead.
func (*PolicyDecision) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{5}
}

func (x *PolicyDecision) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *PolicyDecision) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *PolicyDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PolicyDecision) GetIntent() PolicyDecision_SentinelIntents {
	if x != nil {
		return x.Intent
	}
	return PolicyDecision_SAFE_READ
}

func (x *PolicyDecision) GetEnforcementActions() []string {
	if x != nil {
		return x.EnforcementActions
	}
	return nil
}

type PhaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Phase         PhaseID                `protobuf:"varint,2,opt,name=phase,proto3,enum=nexus.v1.PhaseID" json:"phase,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseRequest) Reset() {
	*x = PhaseRequest{}
	mi := &file_nexus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseRequest) ProtoMessage() {}

func (x *PhaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseRequest.ProtoReflect.Descriptor instead.
func (*PhaseRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{6}
}

func (x *PhaseRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PhaseRequest) GetPhase() PhaseID {
	if x != nil {
		return x.Phase
	}
	return PhaseID_PHASE_UNKNOWN
}

func (x *PhaseRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type PhaseOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhaseId       string                 `protobuf:"bytes,1,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	Status        PhaseOutcome_Status    `protobuf:"varint,2,opt,name=status,proto3,enum=nexus.v1.PhaseOutcome_Status" json:"status,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Mutations     *structpb.Struct       `protobuf:"bytes,4,opt,name=mutations,proto3" json:"mutations,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseOutcome) Reset() {
	*x = PhaseOutcome{}
	mi := &file_nexus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseOutcome) ProtoMessage() {}

func (x *PhaseOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseOutcome.ProtoReflect.Descriptor instead.
func (*PhaseOutcome) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{7}
}

func (x *PhaseOutcome) GetPhaseId() string {
	if x != nil {
		return x.PhaseId
	}
	return ""
}

func (x *PhaseOutcome) GetStatus() PhaseOutcome_Status {
	if x != nil {
		return x.Status
	}
	return PhaseOutcome_SUCCESS
}

func (x *PhaseOutcome) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PhaseOutcome) GetMutations() *structpb.Struct {
	if x != nil {
		return x.Mutations
	}
	return nil
}

func (x *PhaseOutcome) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricEvent) Reset() {
	*x = MetricEvent{}
	mi := &file_nexus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricEvent) ProtoMessage() {}

func (x *MetricEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricEvent.ProtoReflect.Descriptor instead.
func (*MetricEvent) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{8}
}

func (x *MetricEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *MetricEvent) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricEvent) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ResidueCount  uint32                 `protobuf:"varint,3,opt,name=residue_count,json=residueCount,proto3" json:"residue_count,omitempty"` // ✅ v2.1d Hardened: 物理殘留計數
	CleanupTrace  string                 `protobuf:"bytes,4,opt,name=cleanup_trace,json=cleanupTrace,proto3" json:"cleanup_trace,omitempty"`  // ✅ v2.1d Hardened: 清理物理軌跡
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_nexus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{9}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionResponse) GetResidueCount() uint32 {
	if x != nil {
		return x.ResidueCount
	}
	return 0
}

func (x *ActionResponse) GetCleanupTrace() string {
	if x != nil {
		return x.CleanupTrace
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_nexus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=nexus.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_nexus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_nexus_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_nexus_proto protoreflect.FileDescriptor

const file_nexus_proto_rawDesc = "" +
	"\n" +
	"\vnexus.proto\x12\bnexus.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x01\n" +
	"\fLeaseRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vbranch_hint\x18\x02 \x01(\tR\n" +
	"branchHint\x12@\n" +
	"\bmetadata\x18\x03 \x03(\v2$.nexus.v1.LeaseRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\rWorktreeLease\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vbranch_name\x18\x03 \x01(\tR\n" +
	"branchName\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"L\n" +
	"\x0eHarvestRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1f\n" +
	"\vforce_merge\x18\x02 \x01(\bR\n" +
	"forceMerge\"G\n" +
	"\x12CancelLeaseRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x95\x01\n" +
	"\rPolicyRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\x12#\n" +
	"\rintent_prompt\x18\x05 \x01(\tR\fintentPrompt\"\xab\x02\n" +
	"\x0ePolicyDecision\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x14\n" +
	"\x05allow\x18\x02 \x01(\bR\x05allow\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12@\n" +
	"\x06intent\x18\x04 \x01(\x0e2(.nexus.v1.PolicyDecision.SentinelIntentsR\x06intent\x12/\n" +
	"\x13enforcement_actions\x18\x05 \x03(\tR\x12enforcementActions\"W\n" +
	"\x0fSentinelIntents\x12\r\n" +
	"\tSAFE_READ\x10\x00\x12\x13\n" +
	"\x0fDANGEROUS_WRITE\x10\x01\x12\x10\n" +
	"\fHUMAN_REVIEW\x10\x02\x12\x0e\n" +
	"\n" +
	"OOS_ACCESS\x10\x03\"\x83\x01\n" +
	"\fPhaseRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x11.nexus.v1.PhaseIDR\x05phase\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\"\xf0\x02\n" +
	"\fPhaseOutcome\x12\x19\n" +
	"\bphase_id\x18\x01 \x01(\tR\aphaseId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.nexus.v1.PhaseOutcome.StatusR\x06status\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x125\n" +
	"\tmutations\x18\x04 \x01(\v2\x17.google.protobuf.StructR\tmutations\x12=\n" +
	"\ametrics\x18\x05 \x03(\v2#.nexus.v1.PhaseOutcome.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"B\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\x12\x10\n" +
	"\fHUMAN_REVIEW\x10\x02\x12\r\n" +
	"\tESCALATED\x10\x03\"\xf2\x01\n" +
	"\vMetricEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x129\n" +
	"\x06labels\x18\x04 \x03(\v2!.nexus.v1.MetricEvent.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rresidue_count\x18\x03 \x01(\rR\fresidueCount\x12#\n" +
	"\rcleanup_trace\x18\x04 \x01(\tR\fcleanupTrace\"7\n" +
	"\x12HealthCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\x96\x01\n" +
	"\x13HealthCheckResponse\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.nexus.v1.HealthCheckResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02*\x8e\x01\n" +
	"\aPhaseID\x12\x11\n" +
	"\rPHASE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"PHASE_PLAN\x10\x01\x12\x12\n" +
	"\x0ePHASE_RESEARCH\x10\x02\x12\x12\n" +
	"\x0ePHASE_DIAGNOSE\x10\x03\x12\x10\n" +
	"\fPHASE_REPAIR\x10\x04\x12\x0f\n" +
	"\vPHASE_AUDIT\x10\x05\x12\x15\n" +
	"\x11PHASE_CRYSTALLIZE\x10\x062\xec\x02\n" +
	"\tNexusCore\x12@\n" +
	"\rLeaseWorktree\x12\x16.nexus.v1.LeaseRequest\x1a\x17.nexus.v1.WorktreeLease\x12E\n" +
	"\x0fHarvestWorktree\x12\x18.nexus.v1.HarvestRequest\x1a\x18.nexus.v1.ActionResponse\x12E\n" +
	"\vCancelLease\x12\x1c.nexus.v1.CancelLeaseRequest\x1a\x18.nexus.v1.ActionResponse\x12C\n" +
	"\x0eEvaluatePolicy\x12\x17.nexus.v1.PolicyRequest\x1a\x18.nexus.v1.PolicyDecision\x12J\n" +
	"\vHealthCheck\x12\x1c.nexus.v1.HealthCheckRequest\x1a\x1d.nexus.v1.HealthCheckResponse2\x8a\x01\n" +
	"\n" +
	"NexusSwarm\x12:\n" +
	"\bRunPhase\x12\x16.nexus.v1.PhaseRequest\x1a\x16.nexus.v1.PhaseOutcome\x12@\n" +
	"\vEmitMetrics\x12\x15.nexus.v1.MetricEvent\x1a\x18.nexus.v1.ActionResponse(\x01B\x13Z\x11nexus-swarm/nexusb\x06proto3"

var (
	file_nexus_proto_rawDescOnce sync.Once
	file_nexus_proto_rawDescData []byte
)

func file_nexus_proto_rawDescGZIP() []byte {
	file_nexus_proto_rawDescOnce.Do(func() {
		file_nexus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_proto_rawDesc), len(file_nexus_proto_rawDesc)))
	})
	return file_nexus_proto_rawDescData
}

var file_nexus_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_nexus_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_nexus_proto_goTypes = []any{
	(PhaseID)(0),                           // 0: nexus.v1.PhaseID
	(PolicyDecision_SentinelIntents)(0),    // 1: nexus.v1.PolicyDecision.SentinelIntents
	(PhaseOutcome_Status)(0),               // 2: nexus.v1.PhaseOutcome.Status
	(HealthCheckResponse_ServingStatus)(0), // 3: nexus.v1.HealthCheckResponse.ServingStatus
	(*LeaseRequest)(nil),                   // 4: nexus.v1.LeaseRequest
	(*WorktreeLease)(nil),                  // 5: nexus.v1.WorktreeLease
	(*HarvestRequest)(nil),                 // 6: nexus.v1.HarvestRequest
	(*CancelLeaseRequest)(nil),             // 7: nexus.v1.CancelLeaseRequest
	(*PolicyRequest)(nil),                  // 8: nexus.v1.PolicyRequest
	(*PolicyDecision)(nil),                 // 9: nexus.v1.PolicyDecision
	(*PhaseRequest)(nil),                   // 10: nexus.v1.PhaseRequest
	(*PhaseOutcome)(nil),                   // 11: nexus.v1.PhaseOutcome
	(*MetricEvent)(nil),                    // 12: nexus.v1.MetricEvent
	(*ActionResponse)(nil),                 // 13: nexus.v1.ActionResponse
	(*HealthCheckRequest)(nil),             // 14: nexus.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 15: nexus.v1.HealthCheckResponse
	nil,                                    // 16: nexus.v1.LeaseRequest.MetadataEntry
	nil,                                    // 17: nexus.v1.PhaseOutcome.MetricsEntry
	nil,                                    // 18: nexus.v1.MetricEvent.LabelsEntry
	(*timestamppb.Timestamp)(nil),          // 19: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                // 20: google.protobuf.Struct
}
var file_nexus_proto_depIdxs = []int32{
	16, // 0: nexus.v1.LeaseRequest.metadata:type_name -> nexus.v1.LeaseRequest.MetadataEntry
	19, // 1: nexus.v1.WorktreeLease.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 2: nexus.v1.PolicyDecision.intent:type_name -> nexus.v1.PolicyDecision.SentinelIntents
	0,  // 3: nexus.v1.PhaseRequest.phase:type_name -> nexus.v1.PhaseID
	20, // 4: nexus.v1.PhaseRequest.context:type_name -> google.protobuf.Struct
	2,  // 5: nexus.v1.PhaseOutcome.status:type_name -> nexus.v1.PhaseOutcome.Status
	20, // 6: nexus.v1.PhaseOutcome.mutations:type_name -> google.protobuf.Struct
	17, // 7: nexus.v1.PhaseOutcome.metrics:type_name -> nexus.v1.PhaseOutcome.MetricsEntry
	19, // 8: nexus.v1.MetricEvent.timestamp:type_name -> google.protobuf.Timestamp
	18, // 9: nexus.v1.MetricEvent.labels:type_name -> nexus.v1.MetricEvent.LabelsEntry
	3,  // 10: nexus.v1.HealthCheckResponse.status:type_name -> nexus.v1.HealthCheckResponse.ServingStatus
	4,  // 11: nexus.v1.NexusCore.LeaseWorktree:input_type -> nexus.v1.LeaseRequest
	6,  // 12: nexus.v1.NexusCore.HarvestWorktree:input_type -> nexus.v1.HarvestRequest
	7,  // 13: nexus.v1.NexusCore.CancelLease:input_type -> nexus.v1.CancelLeaseRequest
	8,  // 14: nexus.v1.NexusCore.EvaluatePolicy:input_type -> nexus.v1.PolicyRequest
	14, // 15: nexus.v1.NexusCore.HealthCheck:input_type -> nexus.v1.HealthCheckRequest
	10, // 16: nexus.v1.NexusSwarm.RunPhase:input_type -> nexus.v1.PhaseRequest
	12, // 17: nexus.v1.NexusSwarm.EmitMetrics:input_type -> nexus.v1.MetricEvent
	5,  // 18: nexus.v1.NexusCore.LeaseWorktree:output_type -> nexus.v1.WorktreeLease
	13, // 19: nexus.v1.NexusCore.HarvestWorktree:output_type -> nexus.v1.ActionResponse
	13, // 20: nexus.v1.NexusCore.CancelLease:output_type -> nexus.v1.ActionResponse
	9,  // 21: nexus.v1.NexusCore.EvaluatePolicy:output_type -> nexus.v1.PolicyDecision
	15, // 22: nexus.v1.NexusCore.HealthCheck:output_type -> nexus.v1.HealthCheckResponse
	11, // 23: nexus.v1.NexusSwarm.RunPhase:output_type -> nexus.v1.PhaseOutcome
	13, // 24: nexus.v1.NexusSwarm.EmitMetrics:output_type -> nexus.v1.ActionResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_nexus_proto_init() }
func file_nexus_proto_init() {
	if File_nexus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_proto_rawDesc), len(file_nexus_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_nexus_proto_goTypes,
		DependencyIndexes: file_nexus_proto_depIdxs,
		EnumInfos:         file_nexus_proto_enumTypes,
		MessageInfos:      file_nexus_proto_msgTypes,
	}.Build()
	File_nexus_proto = out.File
	file_nexus_proto_goTypes = nil
	file_nexus_proto_depIdxs = nil
}
