# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nexus_pb2 as nexus__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nexus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NexusCoreStub(object):
    """📦 Core System Services (Rust Skeleton)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LeaseWorktree = channel.unary_unary(
                '/nexus.v1.NexusCore/LeaseWorktree',
                request_serializer=nexus__pb2.LeaseRequest.SerializeToString,
                response_deserializer=nexus__pb2.WorktreeLease.FromString,
                _registered_method=True)
        self.HarvestWorktree = channel.unary_unary(
                '/nexus.v1.NexusCore/HarvestWorktree',
                request_serializer=nexus__pb2.HarvestRequest.SerializeToString,
                response_deserializer=nexus__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.CancelLease = channel.unary_unary(
                '/nexus.v1.NexusCore/CancelLease',
                request_serializer=nexus__pb2.CancelLeaseRequest.SerializeToString,
                response_deserializer=nexus__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.EvaluatePolicy = channel.unary_unary(
                '/nexus.v1.NexusCore/EvaluatePolicy',
                request_serializer=nexus__pb2.PolicyRequest.SerializeToString,
                response_deserializer=nexus__pb2.PolicyDecision.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/nexus.v1.NexusCore/HealthCheck',
                request_serializer=nexus__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=nexus__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class NexusCoreServicer(object):
    """📦 Core System Services (Rust Skeleton)
    """

    def LeaseWorktree(self, request, context):
        """Worktree Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HarvestWorktree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelLease(self, request, context):
        """✅ v2.1 Emergency Purge
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluatePolicy(self, request, context):
        """Governance & Policy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health & Monitoring
        ✅ v2.1 K8s Proxy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NexusCoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LeaseWorktree': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaseWorktree,
                    request_deserializer=nexus__pb2.LeaseRequest.FromString,
                    response_serializer=nexus__pb2.WorktreeLease.SerializeToString,
            ),
            'HarvestWorktree': grpc.unary_unary_rpc_method_handler(
                    servicer.HarvestWorktree,
                    request_deserializer=nexus__pb2.HarvestRequest.FromString,
                    response_serializer=nexus__pb2.ActionResponse.SerializeToString,
            ),
            'CancelLease': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelLease,
                    request_deserializer=nexus__pb2.CancelLeaseRequest.FromString,
                    response_serializer=nexus__pb2.ActionResponse.SerializeToString,
            ),
            'EvaluatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluatePolicy,
                    request_deserializer=nexus__pb2.PolicyRequest.FromString,
                    response_serializer=nexus__pb2.PolicyDecision.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=nexus__pb2.HealthCheckRequest.FromString,
                    response_serializer=nexus__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.v1.NexusCore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.v1.NexusCore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NexusCore(object):
    """📦 Core System Services (Rust Skeleton)
    """

    @staticmethod
    def LeaseWorktree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.v1.NexusCore/LeaseWorktree',
            nexus__pb2.LeaseRequest.SerializeToString,
            nexus__pb2.WorktreeLease.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HarvestWorktree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.v1.NexusCore/HarvestWorktree',
            nexus__pb2.HarvestRequest.SerializeToString,
            nexus__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.v1.NexusCore/CancelLease',
            nexus__pb2.CancelLeaseRequest.SerializeToString,
            nexus__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.v1.NexusCore/EvaluatePolicy',
            nexus__pb2.PolicyRequest.SerializeToString,
            nexus__pb2.PolicyDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.v1.NexusCore/HealthCheck',
            nexus__pb2.HealthCheckRequest.SerializeToString,
            nexus__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NexusSwarmStub(object):
    """🛰️ Swarm & Orchestration Services (Go Bus)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunPhase = channel.unary_unary(
                '/nexus.v1.NexusSwarm/RunPhase',
                request_serializer=nexus__pb2.PhaseRequest.SerializeToString,
                response_deserializer=nexus__pb2.PhaseOutcome.FromString,
                _registered_method=True)
        self.EmitMetrics = channel.stream_unary(
                '/nexus.v1.NexusSwarm/EmitMetrics',
                request_serializer=nexus__pb2.MetricEvent.SerializeToString,
                response_deserializer=nexus__pb2.ActionResponse.FromString,
                _registered_method=True)


class NexusSwarmServicer(object):
    """🛰️ Swarm & Orchestration Services (Go Bus)
    """

    def RunPhase(self, request, context):
        """Phase Orchestration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitMetrics(self, request_iterator, context):
        """Telemetry & Metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NexusSwarmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunPhase': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPhase,
                    request_deserializer=nexus__pb2.PhaseRequest.FromString,
                    response_serializer=nexus__pb2.PhaseOutcome.SerializeToString,
            ),
            'EmitMetrics': grpc.stream_unary_rpc_method_handler(
                    servicer.EmitMetrics,
                    request_deserializer=nexus__pb2.MetricEvent.FromString,
                    response_serializer=nexus__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.v1.NexusSwarm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.v1.NexusSwarm', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NexusSwarm(object):
    """🛰️ Swarm & Orchestration Services (Go Bus)
    """

    @staticmethod
    def RunPhase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.v1.NexusSwarm/RunPhase',
            nexus__pb2.PhaseRequest.SerializeToString,
            nexus__pb2.PhaseOutcome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/nexus.v1.NexusSwarm/EmitMetrics',
            nexus__pb2.MetricEvent.SerializeToString,
            nexus__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
