import os


def generate_specs():
    skills_dir = os.path.expanduser("~/.openclaw/skills")
    output_dir = "知識庫/02_Arsenal/Skills_Library"

    print(f"📚 Cataloging skills from: {skills_dir}")

    for item in os.listdir(skills_dir):
        skill_path = os.path.join(skills_dir, item)
        if not os.path.isdir(skill_path):
            continue

        spec_path = os.path.join(output_dir, f"{item}.md")
        skill_md = os.path.join(skill_path, "SKILL.md")

        # 讀取現有定義
        desc = "尚未定義詳細描述"
        if os.path.exists(skill_md):
            with open(skill_md, "r") as f:
                desc = f.read()

        # 掃描腳本
        scripts = []
        script_dir = os.path.join(skill_path, "scripts")
        if os.path.exists(script_dir):
            scripts = [f for f in os.listdir(script_dir) if f.endswith(".py")]

        with open(spec_path, "w") as f:
            f.write(f"# 🛠️ 技能規格: {item}\n\n")
            f.write(f"## 📝 核心定義\n{desc}\n\n")
            f.write("## 📂 實體資產 (Scripts)\n")
            for s in scripts:
                f.write(f"- `scripts/{s}`\n")

            f.write("\n## ⚙️ 執行環境與參數\n")
            f.write(f"- **路徑**: `~/.openclaw/skills/{item}/`\n")
            f.write("- **主要依賴**: `python3`, `openclaw-core`\n")
            f.write(
                f"- **建議測試**: `*task run test_skill.sh ~/.openclaw/skills/{item}/SKILL.md`\n"
            )

            f.write("\n---\n%% Generated by Muse-Core Lvl 12 Skill Spec Generator %%\n")

    print("✅ Skill Catalog updated.")


if __name__ == "__main__":
    generate_specs()
